package com.swv.oscar.repositories.impl;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.TypedQuery;

import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.swv.oscar.dataobject.common.Weo0fcnlBO;
import com.swv.oscar.domain.entity.WeovfactsHeader;
import com.swv.oscar.exceptions.OscarDataAccessException;
import com.swv.oscar.repositories.IWeo0fcnlRepository;
import com.swv.oscar.util.OscarLogger;

/*************************************************************************
 *
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * HCL is a trademark of HCL Company.
 *
 *Copyright © 2017 HCL. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
@Repository
public class Weo0fcnlRepositoryImpl implements IWeo0fcnlRepository {

    private static final OscarLogger LOGGER = OscarLogger.create(Weo0fcnlRepositoryImpl.class);

    @PersistenceContext
    private EntityManager entityMgr;

    /*
      * Method executeExecuteENTRUpdateQuery0
      * @param weo0fcnlBOReq
      * @return weo0fcnlBOResp
      * @throws AppDataAccessException
    */
    @Override
    @Transactional
    public Weo0fcnlBO executeExecuteENTRUpdateQuery0(String query) throws OscarDataAccessException {
        LOGGER.debug("Request: "+ query);
        Weo0fcnlBO  weo0fcnlBOResp = new Weo0fcnlBO();
        try {
            TypedQuery<WeovfactsHeader> typedQuery = (TypedQuery<WeovfactsHeader>)entityMgr.createNativeQuery(query);
            int entityList = typedQuery.executeUpdate();
        } catch (Exception ex) {
            LOGGER.error("Error: " + ex);
            throw new OscarDataAccessException(ex);
        }
        LOGGER.debug("Response: "+weo0fcnlBOResp);
        return weo0fcnlBOResp;
    }
}