package com.swv.oscar.dataobject.batch;

import java.io.Serializable;
import java.util.Date;

/*************************************************************************
 *
 * SWV CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * SWV is a trademark of SWV Company.
 *
 * Copyright © 2017 SWV. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of SWV
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SWV and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SWV.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
public class Weo0neom implements Serializable {

    private String monthOption;
    private String dateIn;
    private String dateOut;
    private int rc;
    private String dateA;
    private int i;
    private String yyyyMm;
    private int yyyy;
//    private String 1xa;
    private int mm;
    public String getMonthOption() {
        return monthOption;
    }

    public void setMonthOption(String monthOption ) {
        this.monthOption = monthOption;
    }

    public String getDateIn() {
		return dateIn;
	}

	public void setDateIn(String dateIn) {
		this.dateIn = dateIn;
	}

	public String getDateOut() {
		return dateOut;
	}

	public void setDateOut(String dateOut) {
		this.dateOut = dateOut;
	}

	public int getRc() {
        return rc;
    }

    public void setRc(int rc ) {
        this.rc = rc;
    }

    public String getDateA() {
		return dateA;
	}

	public void setDateA(String dateA) {
		this.dateA = dateA;
	}

	public int getI() {
        return i;
    }

    public void setI(int i ) {
        this.i = i;
    }

    public String getYyyyMm() {
        return yyyyMm;
    }

    public void setYyyyMm(String yyyyMm ) {
        this.yyyyMm = yyyyMm;
    }

    public int getYyyy() {
        return yyyy;
    }

    public void setYyyy(int yyyy ) {
        this.yyyy = yyyy;
    }

/*    public String get1xa() {
        return 1xa;
    }

    public void set1xa(String 1xa ) {
        this.1xa = 1xa;
    }*/

    public int getMm() {
        return mm;
    }

    public void setMm(int mm ) {
        this.mm = mm;
    }

    @Override
    public String toString() {
        return "Weo0neom [monthOption =" + monthOption + " ,dateIn =" + dateIn + " ,dateOut =" + dateOut + " ,rc =" + rc + " ,dateA =" + dateA + " ,i =" + i + " ,yyyyMm =" + yyyyMm + " ,yyyy =" + yyyy +/* " ,1xa =" + 1xa */ " ,mm =" + mm+ "]";
    }
}