package com.swv.oscar.dataobject.batch;

import java.io.Serializable;
import java.util.List;

import com.swv.oscar.dataobject.common.BaseBO;

/*************************************************************************
 *
 * SWV CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * SWV is a trademark of SWV Company.
 *
 * Copyright © 2017 SWV. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of SWV
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SWV and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SWV.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
public class Weo0neomBO extends BaseBO implements Serializable {

    private List<Weo0neom> weo0neom;
    private List<Weo2nfyr> weo2nfyr;
    
    public List<Weo0neom> getWeo0neom() {
        return weo0neom;
    }

	public List<Weo2nfyr> getWeo2nfyr() {
		return weo2nfyr;
	}

	public void setWeo2nfyr(List<Weo2nfyr> weo2nfyr) {
		this.weo2nfyr = weo2nfyr;
	}

	public void setWeo0neom(List<Weo0neom> weo0neom) {
		this.weo0neom = weo0neom;
	}

	@Override
	public String toString() {
		return "Weo0neomBO [weo0neom=" + weo0neom + ", weo2nfyr=" + weo2nfyr + "]";
	}
}