package com.swv.oscar.dataobject.batch;

import java.io.Serializable;

/*************************************************************************
 *
 * SWV CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * SWV is a trademark of SWV Company.
 *
 * Copyright © 2017 SWV. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of SWV
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SWV and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SWV.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
public class Weo0nenv implements Serializable {

    private String fname;
    private String dbt;
    private String fnrt;
    private String hname;
    private String qty;
    private Integer i;
    private Integer rc;
    private String env;
    public String getFname() {
        return fname;
    }

    public void setFname(String fname ) {
        this.fname = fname;
    }

    public String getDbt() {
        return dbt;
    }

    public void setDbt(String dbt ) {
        this.dbt = dbt;
    }

    public String getFnrt() {
        return fnrt;
    }

    public void setFnrt(String fnrt ) {
        this.fnrt = fnrt;
    }

    public String getHname() {
        return hname;
    }

    public void setHname(String hname ) {
        this.hname = hname;
    }

    public String getQty() {
        return qty;
    }

    public void setQty(String qty ) {
        this.qty = qty;
    }

    public Integer getI() {
        return i;
    }

    public void setI(Integer i ) {
        this.i = i;
    }

    public Integer getRc() {
        return rc;
    }

    public void setRc(Integer rc ) {
        this.rc = rc;
    }

    public String getEnv() {
        return env;
    }

    public void setEnv(String env ) {
        this.env = env;
    }

    @Override
    public String toString() {
        return "Weo0nenv [fname =" + fname + " ,dbt =" + dbt + " ,fnrt =" + fnrt + " ,hname =" + hname + " ,qty =" + qty + " ,i =" + i + " ,rc =" + rc + " ,env =" + env+ "]";
    }
}