package com.swv.oscar.dataobject.batch;

import java.io.Serializable;

/*************************************************************************
 *
 * SWV CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * SWV is a trademark of SWV Company.
 *
 * Copyright © 2017 SWV. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of SWV
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SWV and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SWV.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
public class Weo0chkp implements Serializable {

    private Integer gRc;
    private String gEnv;
    private String gSqlid;
    private String gSqlstmt;
    private String gProgram;
    private String gCommitMax;
    private String gStartTime;
    private String weo0chkpGCommitMax;
    private String weo0chkpGStartTime;
    private String gTracDate;
    private String gFromDate;
    private String gTodaysDt;
    private String gCommitData;
    private String gEndTime;
    private String weo0chkpGTodaysDt;
    private String weo0chkpGCommitData;
    private String weo0chkpGEndTime;
    private String commitData;
    public Integer getgRc() {
        return gRc;
    }

    public void setgRc(Integer gRc ) {
        this.gRc = gRc;
    }

    public String getgEnv() {
        return gEnv;
    }

    public void setgEnv(String gEnv ) {
        this.gEnv = gEnv;
    }

    public String getgSqlid() {
        return gSqlid;
    }

    public void setgSqlid(String gSqlid ) {
        this.gSqlid = gSqlid;
    }

    public String getgSqlstmt() {
        return gSqlstmt;
    }

    public void setgSqlstmt(String gSqlstmt ) {
        this.gSqlstmt = gSqlstmt;
    }

    public String getgProgram() {
        return gProgram;
    }

    public void setgProgram(String gProgram ) {
        this.gProgram = gProgram;
    }

    public String getgCommitMax() {
        return gCommitMax;
    }

    public void setgCommitMax(String gCommitMax ) {
        this.gCommitMax = gCommitMax;
    }

    public String getgStartTime() {
        return gStartTime;
    }

    public void setgStartTime(String gStartTime ) {
        this.gStartTime = gStartTime;
    }

    public String getWeo0chkpGCommitMax() {
        return weo0chkpGCommitMax;
    }

    public void setWeo0chkpGCommitMax(String weo0chkpGCommitMax ) {
        this.weo0chkpGCommitMax = weo0chkpGCommitMax;
    }

    public String getWeo0chkpGStartTime() {
        return weo0chkpGStartTime;
    }

    public void setWeo0chkpGStartTime(String weo0chkpGStartTime ) {
        this.weo0chkpGStartTime = weo0chkpGStartTime;
    }

    public String getgTracDate() {
        return gTracDate;
    }

    public void setgTracDate(String gTracDate ) {
        this.gTracDate = gTracDate;
    }

    public String getgFromDate() {
        return gFromDate;
    }

    public void setgFromDate(String gFromDate ) {
        this.gFromDate = gFromDate;
    }

    public String getgTodaysDt() {
        return gTodaysDt;
    }

    public void setgTodaysDt(String gTodaysDt ) {
        this.gTodaysDt = gTodaysDt;
    }

    public String getgCommitData() {
        return gCommitData;
    }

    public void setgCommitData(String gCommitData ) {
        this.gCommitData = gCommitData;
    }

    public String getgEndTime() {
        return gEndTime;
    }

    public void setgEndTime(String gEndTime ) {
        this.gEndTime = gEndTime;
    }

    public String getWeo0chkpGTodaysDt() {
        return weo0chkpGTodaysDt;
    }

    public void setWeo0chkpGTodaysDt(String weo0chkpGTodaysDt ) {
        this.weo0chkpGTodaysDt = weo0chkpGTodaysDt;
    }

    public String getWeo0chkpGCommitData() {
        return weo0chkpGCommitData;
    }

    public void setWeo0chkpGCommitData(String weo0chkpGCommitData ) {
        this.weo0chkpGCommitData = weo0chkpGCommitData;
    }

    public String getWeo0chkpGEndTime() {
        return weo0chkpGEndTime;
    }

    public void setWeo0chkpGEndTime(String weo0chkpGEndTime ) {
        this.weo0chkpGEndTime = weo0chkpGEndTime;
    }

    public String getCommitData() {
        return commitData;
    }

    public void setCommitData(String commitData ) {
        this.commitData = commitData;
    }

    @Override
    public String toString() {
        return "Weo0chkp [gRc =" + gRc + " ,gEnv =" + gEnv + " ,gSqlid =" + gSqlid + " ,gSqlstmt =" + gSqlstmt + " ,gProgram =" + gProgram + " ,gCommitMax =" + gCommitMax + " ,gStartTime =" + gStartTime + " ,weo0chkpGCommitMax =" + weo0chkpGCommitMax + " , =" + " ,weo0chkpGStartTime =" + weo0chkpGStartTime + " ,gTracDate =" + gTracDate + " ,gFromDate =" + gFromDate + " ,gTodaysDt =" + gTodaysDt + " ,gCommitData =" + gCommitData + " ,gEndTime =" + gEndTime + " ,weo0chkpGTodaysDt =" + weo0chkpGTodaysDt + " ,weo0chkpGCommitData =" + weo0chkpGCommitData + " ,weo0chkpGEndTime =" + weo0chkpGEndTime + " ,commitData =" + commitData+ "]";
    }
}