package com.swv.oscar.dataobject.batch;

import java.io.Serializable;
import java.util.Arrays;

/*************************************************************************
 *
 * SWV CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * SWV is a trademark of SWV Company.
 *
 * Copyright © 2017 SWV. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of SWV
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SWV and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SWV.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
public class Weo2nfyr implements Serializable {

    private String ffyStartDate;
    private String ffyEndDate;
    private String fiscalYear;
    private int fiscalQuarter;
    private String mthOrQtr;
    private String fyStart;
    private String fysYyyy;
    private String fyEnd;
    private String fyeYyyy;
    private String fill1;
    private String fyeMm;
    private String fill2;
    private String fyeDd;
    private String todaysDate;
    private String todaysYyyy;
    private int todaysYyyyn;
    private String tdyYm;
    private String todaysMm;
    private int todaysMmN;
    private String eomDate;
    private String eomMm;
    private String eomDd;
    private int rc;
    private String weo2nfyrTodaysDate;
    private int[] mthQtrArray = {1,4,7,10};
    
    public String getFfyStartDate() {
        return ffyStartDate;
    }

    public void setFfyStartDate(String ffyStartDate ) {
        this.ffyStartDate = ffyStartDate;
    }

    public String getFfyEndDate() {
        return ffyEndDate;
    }

    public void setFfyEndDate(String ffyEndDate ) {
        this.ffyEndDate = ffyEndDate;
    }

    public String getFiscalYear() {
        return fiscalYear;
    }

    public void setFiscalYear(String fiscalYear ) {
        this.fiscalYear = fiscalYear;
    }

    public int getFiscalQuarter() {
        return fiscalQuarter;
    }

    public void setFiscalQuarter(int fiscalQuarter ) {
        this.fiscalQuarter = fiscalQuarter;
    }

    public String getMthOrQtr() {
        return mthOrQtr;
    }

    public void setMthOrQtr(String mthOrQtr ) {
        this.mthOrQtr = mthOrQtr;
    }

    public String getFyStart() {
        return fyStart;
    }

    public void setFyStart(String fyStart ) {
        this.fyStart = fyStart;
    }

    public String getFysYyyy() {
        return fysYyyy;
    }

    public void setFysYyyy(String fysYyyy ) {
        this.fysYyyy = fysYyyy;
    }

    public String getFyEnd() {
        return fyEnd;
    }

    public void setFyEnd(String fyEnd ) {
        this.fyEnd = fyEnd;
    }

    public String getFyeYyyy() {
        return fyeYyyy;
    }

    public void setFyeYyyy(String fyeYyyy ) {
        this.fyeYyyy = fyeYyyy;
    }

    public String getFill1() {
        return fill1;
    }

    public void setFill1(String fill1 ) {
        this.fill1 = fill1;
    }

    public String getFyeMm() {
        return fyeMm;
    }

    public void setFyeMm(String fyeMm ) {
        this.fyeMm = fyeMm;
    }

    public String getFill2() {
        return fill2;
    }

    public void setFill2(String fill2 ) {
        this.fill2 = fill2;
    }

    public String getFyeDd() {
        return fyeDd;
    }

    public void setFyeDd(String fyeDd ) {
        this.fyeDd = fyeDd;
    }

    public String getTodaysDate() {
        return todaysDate;
    }

    public void setTodaysDate(String todaysDate ) {
        this.todaysDate = todaysDate;
    }

    public String getTodaysYyyy() {
        return todaysYyyy;
    }

    public void setTodaysYyyy(String todaysYyyy ) {
        this.todaysYyyy = todaysYyyy;
    }

    public int getTodaysYyyyn() {
        return todaysYyyyn;
    }

    public void setTodaysYyyyn(int todaysYyyyn ) {
        this.todaysYyyyn = todaysYyyyn;
    }

    public String getTdyYm() {
        return tdyYm;
    }

    public void setTdyYm(String tdyYm ) {
        this.tdyYm = tdyYm;
    }

    public String getTodaysMm() {
        return todaysMm;
    }

    public void setTodaysMm(String todaysMm ) {
        this.todaysMm = todaysMm;
    }

    public int getTodaysMmN() {
        return todaysMmN;
    }

    public void setTodaysMmN(int todaysMmN ) {
        this.todaysMmN = todaysMmN;
    }

    public String getEomDate() {
        return eomDate;
    }

    public void setEomDate(String eomDate ) {
        this.eomDate = eomDate;
    }

    public String getEomMm() {
        return eomMm;
    }

    public void setEomMm(String eomMm ) {
        this.eomMm = eomMm;
    }

    public String getEomDd() {
        return eomDd;
    }

    public void setEomDd(String eomDd ) {
        this.eomDd = eomDd;
    }

    public int getRc() {
        return rc;
    }

    public void setRc(int rc ) {
        this.rc = rc;
    }

    public String getWeo2nfyrTodaysDate() {
        return weo2nfyrTodaysDate;
    }

    public void setWeo2nfyrTodaysDate(String weo2nfyrTodaysDate ) {
        this.weo2nfyrTodaysDate = weo2nfyrTodaysDate;
    }
    
	public int[] getMthQtrArray() {
		return mthQtrArray;
	}

	public void setMthQtrArray(int[] mthQtrArray) {
		this.mthQtrArray = mthQtrArray;
	}

	@Override
	public String toString() {
		return "Weo2nfyr [ffyStartDate=" + ffyStartDate + ", ffyEndDate=" + ffyEndDate + ", fiscalYear=" + fiscalYear
				+ ", fiscalQuarter=" + fiscalQuarter + ", mthOrQtr=" + mthOrQtr + ", fyStart=" + fyStart + ", fysYyyy="
				+ fysYyyy + ", fyEnd=" + fyEnd + ", fyeYyyy=" + fyeYyyy + ", fill1=" + fill1 + ", fyeMm=" + fyeMm
				+ ", fill2=" + fill2 + ", fyeDd=" + fyeDd + ", todaysDate=" + todaysDate + ", todaysYyyy=" + todaysYyyy
				+ ", todaysYyyyn=" + todaysYyyyn + ", tdyYm=" + tdyYm + ", todaysMm=" + todaysMm + ", todaysMmN="
				+ todaysMmN + ", eomDate=" + eomDate + ", eomMm=" + eomMm + ", eomDd=" + eomDd + ", rc=" + rc
				+ ", weo2nfyrTodaysDate=" + weo2nfyrTodaysDate + ", mthQtrArray=" + Arrays.toString(mthQtrArray) + "]";
	}
}