package com.swv.oscar.dataobject.batch;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/*************************************************************************
 *
 * SWV CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * SWV is a trademark of SWV Company.
 *
 * Copyright © 2017 SWV. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of SWV
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SWV and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SWV.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
public class Weo2p57a implements Serializable {

    private String sectionA;
    private String line1;
    private int totCasesCurr;
    private int totCasesFrmr;
    private int totCasesNevr;
    private String line1a;
    private int uiCasesCurr;
    private int uiCasesFrmr;
    private int uiCasesNevr;
    private String line1b;
    private int urCasesCurr;
    private int urCasesFrmr;
    private int urCasesNevr;
    private String line1c;
    private int totMCasesNevr;
    private String line1d;
    private int trInitCurr;
    private int trInitFrmr;
    private int trInitNevr;
    private String line1e;
    private int trRecCurr;
    private int trRecFrmr;
    private int trRecNevr;
    private String line1f;
    private int interInit;
    private String line1g;
    private int interRec;
    private String line2;
    private int crtordCasesCurr;
    private int crtordCasesFrmr;
    private int crtordCasesNevr;
    private String line2a;
    private int crtordUiCasCurr;
    private int crtordUiCasFrmr;
    private int crtordUiCasNevr;
    private String line2b;
    private int crtordUrCasCurr;
    private int crtordUrCasFrmr;
    private int crtordUrCasNevr;
    private String line2c;
    private int zeroOrdCaseCurr;
    private int zeroOrdCaseFrmr;
    private int zeroOrdCaseNevr;
    private String line2d;
    private int crtordMCasNevr;
    private String line2e;
    private int arrsOnlyOrdr;
    private String line2f;
    private int trInitOrdrCurr;
    private int trInitOrdrFrmr;
    private int trInitOrdrNevr;
    private String line2g;
    private int trRecOrdrCurr;
    private int trRecOrdrFrmr;
    private int trRecOrdrNevr;
    private String line2h;
    private int interInitOrdr;
    private String line2i;
    private int interRecOrdr;
    private String line3;
    private int noJursCasesCurr;
    private int noJursCasesFrmr;
    private int noJursCasesNevr;
    private String caseType;
    private String apStatusCd;
    private String oosCaseType;
    private String afdcCaseNbr;
    private String statusChgDate;
    private String assistType;
    private String caseStartDate;
    private int insuOrderedCount;
    private String fyStartTimestamp;
    private String fyEndTimestamp;
    private String oldValueCs;
    private String oldCaseStatus;
    private String oldValueOos;
    private String oldOosType;
    private String oldRestOos;
    private int totalCasesRead;
    private int childAge;
    private String childDob;
    private int childDobYyyy;
    private String childDobYm;
    private int childDobMm;
    private String childDobMd;
    private int childDobDd;
    private String flags;
    private boolean childUnderAge18;
    private boolean hearingExists;
    private boolean grantAmountExists;
    private boolean includeInLine2;
    private boolean includeInLine2c;
    private boolean includeInLine2d;
    private boolean includeInLine3;
    private boolean includedInLine2;
    private boolean includedInLine2a;
    private boolean includedInLine2b;
    private boolean includedInLine2c;
    private boolean includedInLine2d;
    private boolean includedInLine2e;
    private boolean includedInLine2h;
    private boolean includedInLine2i;
    private Double chSupArrs;
    private Double medSupArrs;
    private String startDate;
    private String endDate;
    private String grantStart;
    private int monthsActive;
    private String calcStart;
    private String calcStartYyyy;
    private int calcStartYyyyn;
    private String csYm;
    private String calcStartMm;
    private int calcStartMmn;
    private String csMn;
    private String calcStartDd;
    private String calcEnd;
    private String calcEndYyyy;
    private int calcEndYyyyn;
    private String ceYm;
    private String calcEndMm;
    private int calcEndMmn;
    private String ceMn;
    private String calcEndDd;
    private String sept;
    private String septYyyy;
    private String sYm;
    private String septMm;
    private String sMn;
    private String septDd;
    private boolean obligationExists;
    private boolean notOnly;
    private boolean moved;
    private int exists;
    private String status;
    private Double totAArrsDue;
    private Double totAArrsRcvd;
    private Double totNArrsDue;
    private Double totNArrsRcvd;
    private Double afdcChSupDelq;
    private Double afdcChSupInGrace;
    private Double afdcMedDue;
    private Double afdcMedRcvd;
    private Double afdcMdSupDelq;
    private Double afdcMdSupInGrace;
    private Double nafdcChSupDelq;
    private Double nafdcChSupInGrace;
    private Double nafdcMedDue;
    private Double nafdcMedRcvd;
    private Double nafdcMdSupDelq;
    private Double nafdcMdSupInGrace;
    private Double totACsDelqRcvd;
    private Double totNCsDelqRcvd;
    private Double totAMsDelqRcvd;
    private Double totNMsDelqRcvd;
    private Double aCsInGraceRcvd;
    private Double nCsInGraceRcvd;
    private Double aMsInGraceRcvd;
    private Double nMsInGraceRcvd;
    private Double totNArrsCint;
    private Double totNArrsSint;
    private Double mthNArrsCint;
    private Double totNMedCint;
    private Double totNMedSint;
    private Double mthNMedCint;
    private Double tcArsDue;
    private Double tcArsRcv;
    private Double tcChSupDel;
    private Double tcCsDelRcv;
    private Double uArsDue;
    private Double uArsRcv;
    private Double uChSupDel;
    private Double uCsDelRcv;
    private Double nArsCintRcv;
    private Double nArsSintRcv;
    private Double mthNArsIntRcv;
    private Double tcArsCint;
    private Double tcArsCintRcv;
    private Double tcArsSint;
    private Double tcArsSintRcv;
    private Double mthTcArsInt;
    private Double mthTcArsIntRcv;
    private Double uArsCint;
    private Double uArsCintRcv;
    private Double uArsSint;
    private Double uArsSintRcv;
    private Double mthUArsInt;
    private Double mthUArsIntRcv;
    private Double tcChSupInGrace;
    private Double tcCsInGraceRcv;
    private Double uChSupInGrace;
    private Double uCsInGraceRcv;
    private Double nMedCintRcv;
    private Double nMedSintRcv;
    private Double mthNMedIntRcv;
    private String fyStart;
    private String fysYyyy;
    private String fysYm;
    private String fysMm;
    private String fysMd;
    private String fysDd;
    private String fyEnd;
    private String fyeYyyy;
    private String fyeYm;
    private String fyeMm;
    private String fyeMd;
    private String fyeDd;
    private int fyQtr;
    private String work;
    private String caseIda;
    private int caseId;
    private String cdn;
    private String cdn9;
    private String cdn2;
    private int cnt;
    private int oblgCnt;
    private String oblgType;
    private String oldValue;
    private String oldCaseType;
    private String oldRes2;
    private String newValue;
    private String newCaseType;
    private String newTypeDate;
    private String newRest2;
    private Double amount;
    private String obligationType;
    private String orderType;
    private String csExtend18;
    private String serviceType;
    private String apCountry;
    private String ctCountry;
    private Date dateVar;
    private Date dateVar2;
    private int pagenumber;
    private String changedTime;
    private String timeOfEvent;
    private String commitData;
    private int nbrOfTables;
    private List<String> viewArray;
    private String respFips;
    private String initFips;
    private String mthOrQtr;
    private String fiscalYear;
    private String weo2p57aCnt;
    private String gApPin;
    private String gCtPin;
    private String weo2p57aCaseId;
    private String weo2p57aCaseType;
    private String weo2p57aStatus;
    private String weo2p57aCdn;
    private String weo2p57aApStatusCd;
    private String weo2p57aOosCaseType;
    private String weo2p57aAfdcCaseNbr;
    private String weo2p57aCaseStartDate;
    private String weo2p57aAssistType;
    private String weo2p57aStatusChgDate;
    private String weo2p57aServiceType;
    private String weo2p57aGApPin;
    private String weo2p57aGCtPin;
    private String weo2p57aApCountry;
    private String weo2p57aCtCountry;
    private String weo2p57aAmount;
    private String weo2p57aStartDate;
    private String weo2p57aEndDate;
    private String weo2p57aObligationType;
    private String weo2p57aOrderType;
    private String weo2p57aCsExtend18;
    private String weo2p57aRespFips;
    private String weo2p57aInitFips;
    private String weo2p57aAfdcChSupDelq;
    private String weo2p57aAfdcChSupInGrace;
    private String weo2p57aAfdcMedDue;
    private String weo2p57aAfdcMedRcvd;
    private String weo2p57aAfdcMdSupDelq;
    private String weo2p57aAfdcMdSupInGrace;
    private String weo2p57aNafdcChSupDelq;
    private String weo2p57aNafdcChSupInGrace;
    private String weo2p57aNafdcMedDue;
    private String weo2p57aNafdcMedRcvd;
    private String weo2p57aNafdcMdSupDelq;
    private String weo2p57aNafdcMdSupInGrace;
    private String weo2p57aTotACsDelqRcvd;
    private String weo2p57aTotAMsDelqRcvd;
    private String weo2p57aACsInGraceRcvd;
    private String weo2p57aAMsInGraceRcvd;
    private String weo2p57aTotNCsDelqRcvd;
    private String weo2p57aTotNMsDelqRcvd;
    private String weo2p57aNCsInGraceRcvd;
    private String weo2p57aNMsInGraceRcvd;
    private String weo2p57aTotNArrsCint;
    private String weo2p57aTotNArrsSint;
    private String weo2p57aMthNArrsCint;
    private String weo2p57aTotNMedCint;
    private String weo2p57aTotNMedSint;
    private String weo2p57aMthNMedCint;
    private String weo2p57aTotAArrsDue;
    private String weo2p57aTotAArrsRcvd;
    private String weo2p57aTotNArrsDue;
    private String weo2p57aTotNArrsRcvd;
    private String weo2p57aTcArsDue;
    private String weo2p57aTcArsRcv;
    private String weo2p57aTcChSupDel;
    private String weo2p57aTcCsDelRcv;
    private String weo2p57aUArsDue;
    private String weo2p57aUArsRcv;
    private String weo2p57aUChSupDel;
    private String weo2p57aUCsDelRcv;
    private String weo2p57aNArsCintRcv;
    private String weo2p57aNArsSintRcv;
    private String weo2p57aMthNArsIntRcv;
    private String weo2p57aTcArsCint;
    private String weo2p57aTcArsCintRcv;
    private String weo2p57aTcArsSint;
    private String weo2p57aTcArsSintRcv;
    private String weo2p57aMthTcArsInt;
    private String weo2p57aMthTcArsIntRcv;
    private String weo2p57aUArsCint;
    private String weo2p57aUArsCintRcv;
    private String weo2p57aUArsSint;
    private String weo2p57aUArsSintRcv;
    private String weo2p57aMthUArsInt;
    private String weo2p57aMthUArsIntRcv;
    private String weo2p57aTcChSupInGrace;
    private String weo2p57aTcCsInGraceRcv;
    private String weo2p57aUChSupInGrace;
    private String weo2p57aUCsInGraceRcv;
    private String weo2p57aNMedCintRcv;
    private String weo2p57aNMedSintRcv;
    private String weo2p57aMthNMedIntRcv;
    private String weo2p57aExists;
    private String weo2p57aOldValueCs;
    private String weo2p57aTimeOfEvent;
    private String weo2p57aOldValue;
    private String weo2p57aNewValue;
    private String weo2p57aOldValueOos;
    private String weo2p57aChildDob;
    private String weo2p57aInsuOrderedCount;
    private String weo2p57aGrantStart;
    private String weo2p57aOblgCnt;
    private String weo2p57aOblgType;
	public String getSectionA() {
		return sectionA;
	}
	public void setSectionA(String sectionA) {
		this.sectionA = sectionA;
	}
	public String getLine1() {
		return line1;
	}
	public void setLine1(String line1) {
		this.line1 = line1;
	}
	public int getTotCasesCurr() {
		return totCasesCurr;
	}
	public void setTotCasesCurr(int totCasesCurr) {
		this.totCasesCurr = totCasesCurr;
	}
	public int getTotCasesFrmr() {
		return totCasesFrmr;
	}
	public void setTotCasesFrmr(int totCasesFrmr) {
		this.totCasesFrmr = totCasesFrmr;
	}
	public int getTotCasesNevr() {
		return totCasesNevr;
	}
	public void setTotCasesNevr(int totCasesNevr) {
		this.totCasesNevr = totCasesNevr;
	}
	public String getLine1a() {
		return line1a;
	}
	public void setLine1a(String line1a) {
		this.line1a = line1a;
	}
	public int getUiCasesCurr() {
		return uiCasesCurr;
	}
	public void setUiCasesCurr(int uiCasesCurr) {
		this.uiCasesCurr = uiCasesCurr;
	}
	public int getUiCasesFrmr() {
		return uiCasesFrmr;
	}
	public void setUiCasesFrmr(int uiCasesFrmr) {
		this.uiCasesFrmr = uiCasesFrmr;
	}
	public int getUiCasesNevr() {
		return uiCasesNevr;
	}
	public void setUiCasesNevr(int uiCasesNevr) {
		this.uiCasesNevr = uiCasesNevr;
	}
	public String getLine1b() {
		return line1b;
	}
	public void setLine1b(String line1b) {
		this.line1b = line1b;
	}
	public int getUrCasesCurr() {
		return urCasesCurr;
	}
	public void setUrCasesCurr(int urCasesCurr) {
		this.urCasesCurr = urCasesCurr;
	}
	public int getUrCasesFrmr() {
		return urCasesFrmr;
	}
	public void setUrCasesFrmr(int urCasesFrmr) {
		this.urCasesFrmr = urCasesFrmr;
	}
	public int getUrCasesNevr() {
		return urCasesNevr;
	}
	public void setUrCasesNevr(int urCasesNevr) {
		this.urCasesNevr = urCasesNevr;
	}
	public String getLine1c() {
		return line1c;
	}
	public void setLine1c(String line1c) {
		this.line1c = line1c;
	}
	public int getTotMCasesNevr() {
		return totMCasesNevr;
	}
	public void setTotMCasesNevr(int totMCasesNevr) {
		this.totMCasesNevr = totMCasesNevr;
	}
	public String getLine1d() {
		return line1d;
	}
	public void setLine1d(String line1d) {
		this.line1d = line1d;
	}
	public int getTrInitCurr() {
		return trInitCurr;
	}
	public void setTrInitCurr(int trInitCurr) {
		this.trInitCurr = trInitCurr;
	}
	public int getTrInitFrmr() {
		return trInitFrmr;
	}
	public void setTrInitFrmr(int trInitFrmr) {
		this.trInitFrmr = trInitFrmr;
	}
	public int getTrInitNevr() {
		return trInitNevr;
	}
	public void setTrInitNevr(int trInitNevr) {
		this.trInitNevr = trInitNevr;
	}
	public String getLine1e() {
		return line1e;
	}
	public void setLine1e(String line1e) {
		this.line1e = line1e;
	}
	public int getTrRecCurr() {
		return trRecCurr;
	}
	public void setTrRecCurr(int trRecCurr) {
		this.trRecCurr = trRecCurr;
	}
	public int getTrRecFrmr() {
		return trRecFrmr;
	}
	public void setTrRecFrmr(int trRecFrmr) {
		this.trRecFrmr = trRecFrmr;
	}
	public int getTrRecNevr() {
		return trRecNevr;
	}
	public void setTrRecNevr(int trRecNevr) {
		this.trRecNevr = trRecNevr;
	}
	public String getLine1f() {
		return line1f;
	}
	public void setLine1f(String line1f) {
		this.line1f = line1f;
	}
	public int getInterInit() {
		return interInit;
	}
	public void setInterInit(int interInit) {
		this.interInit = interInit;
	}
	public String getLine1g() {
		return line1g;
	}
	public void setLine1g(String line1g) {
		this.line1g = line1g;
	}
	public int getInterRec() {
		return interRec;
	}
	public void setInterRec(int interRec) {
		this.interRec = interRec;
	}
	public String getLine2() {
		return line2;
	}
	public void setLine2(String line2) {
		this.line2 = line2;
	}
	public int getCrtordCasesCurr() {
		return crtordCasesCurr;
	}
	public void setCrtordCasesCurr(int crtordCasesCurr) {
		this.crtordCasesCurr = crtordCasesCurr;
	}
	public int getCrtordCasesFrmr() {
		return crtordCasesFrmr;
	}
	public void setCrtordCasesFrmr(int crtordCasesFrmr) {
		this.crtordCasesFrmr = crtordCasesFrmr;
	}
	public int getCrtordCasesNevr() {
		return crtordCasesNevr;
	}
	public void setCrtordCasesNevr(int crtordCasesNevr) {
		this.crtordCasesNevr = crtordCasesNevr;
	}
	public String getLine2a() {
		return line2a;
	}
	public void setLine2a(String line2a) {
		this.line2a = line2a;
	}
	public int getCrtordUiCasCurr() {
		return crtordUiCasCurr;
	}
	public void setCrtordUiCasCurr(int crtordUiCasCurr) {
		this.crtordUiCasCurr = crtordUiCasCurr;
	}
	public int getCrtordUiCasFrmr() {
		return crtordUiCasFrmr;
	}
	public void setCrtordUiCasFrmr(int crtordUiCasFrmr) {
		this.crtordUiCasFrmr = crtordUiCasFrmr;
	}
	public int getCrtordUiCasNevr() {
		return crtordUiCasNevr;
	}
	public void setCrtordUiCasNevr(int crtordUiCasNevr) {
		this.crtordUiCasNevr = crtordUiCasNevr;
	}
	public String getLine2b() {
		return line2b;
	}
	public void setLine2b(String line2b) {
		this.line2b = line2b;
	}
	public int getCrtordUrCasCurr() {
		return crtordUrCasCurr;
	}
	public void setCrtordUrCasCurr(int crtordUrCasCurr) {
		this.crtordUrCasCurr = crtordUrCasCurr;
	}
	public int getCrtordUrCasFrmr() {
		return crtordUrCasFrmr;
	}
	public void setCrtordUrCasFrmr(int crtordUrCasFrmr) {
		this.crtordUrCasFrmr = crtordUrCasFrmr;
	}
	public int getCrtordUrCasNevr() {
		return crtordUrCasNevr;
	}
	public void setCrtordUrCasNevr(int crtordUrCasNevr) {
		this.crtordUrCasNevr = crtordUrCasNevr;
	}
	public String getLine2c() {
		return line2c;
	}
	public void setLine2c(String line2c) {
		this.line2c = line2c;
	}
	public int getZeroOrdCaseCurr() {
		return zeroOrdCaseCurr;
	}
	public void setZeroOrdCaseCurr(int zeroOrdCaseCurr) {
		this.zeroOrdCaseCurr = zeroOrdCaseCurr;
	}
	public int getZeroOrdCaseFrmr() {
		return zeroOrdCaseFrmr;
	}
	public void setZeroOrdCaseFrmr(int zeroOrdCaseFrmr) {
		this.zeroOrdCaseFrmr = zeroOrdCaseFrmr;
	}
	public int getZeroOrdCaseNevr() {
		return zeroOrdCaseNevr;
	}
	public void setZeroOrdCaseNevr(int zeroOrdCaseNevr) {
		this.zeroOrdCaseNevr = zeroOrdCaseNevr;
	}
	public String getLine2d() {
		return line2d;
	}
	public void setLine2d(String line2d) {
		this.line2d = line2d;
	}
	public int getCrtordMCasNevr() {
		return crtordMCasNevr;
	}
	public void setCrtordMCasNevr(int crtordMCasNevr) {
		this.crtordMCasNevr = crtordMCasNevr;
	}
	public String getLine2e() {
		return line2e;
	}
	public void setLine2e(String line2e) {
		this.line2e = line2e;
	}
	public int getArrsOnlyOrdr() {
		return arrsOnlyOrdr;
	}
	public void setArrsOnlyOrdr(int arrsOnlyOrdr) {
		this.arrsOnlyOrdr = arrsOnlyOrdr;
	}
	public String getLine2f() {
		return line2f;
	}
	public void setLine2f(String line2f) {
		this.line2f = line2f;
	}
	public int getTrInitOrdrCurr() {
		return trInitOrdrCurr;
	}
	public void setTrInitOrdrCurr(int trInitOrdrCurr) {
		this.trInitOrdrCurr = trInitOrdrCurr;
	}
	public int getTrInitOrdrFrmr() {
		return trInitOrdrFrmr;
	}
	public void setTrInitOrdrFrmr(int trInitOrdrFrmr) {
		this.trInitOrdrFrmr = trInitOrdrFrmr;
	}
	public int getTrInitOrdrNevr() {
		return trInitOrdrNevr;
	}
	public void setTrInitOrdrNevr(int trInitOrdrNevr) {
		this.trInitOrdrNevr = trInitOrdrNevr;
	}
	public String getLine2g() {
		return line2g;
	}
	public void setLine2g(String line2g) {
		this.line2g = line2g;
	}
	public int getTrRecOrdrCurr() {
		return trRecOrdrCurr;
	}
	public void setTrRecOrdrCurr(int trRecOrdrCurr) {
		this.trRecOrdrCurr = trRecOrdrCurr;
	}
	public int getTrRecOrdrFrmr() {
		return trRecOrdrFrmr;
	}
	public void setTrRecOrdrFrmr(int trRecOrdrFrmr) {
		this.trRecOrdrFrmr = trRecOrdrFrmr;
	}
	public int getTrRecOrdrNevr() {
		return trRecOrdrNevr;
	}
	public void setTrRecOrdrNevr(int trRecOrdrNevr) {
		this.trRecOrdrNevr = trRecOrdrNevr;
	}
	public String getLine2h() {
		return line2h;
	}
	public void setLine2h(String line2h) {
		this.line2h = line2h;
	}
	public int getInterInitOrdr() {
		return interInitOrdr;
	}
	public void setInterInitOrdr(int interInitOrdr) {
		this.interInitOrdr = interInitOrdr;
	}
	public String getLine2i() {
		return line2i;
	}
	public void setLine2i(String line2i) {
		this.line2i = line2i;
	}
	public int getInterRecOrdr() {
		return interRecOrdr;
	}
	public void setInterRecOrdr(int interRecOrdr) {
		this.interRecOrdr = interRecOrdr;
	}
	public String getLine3() {
		return line3;
	}
	public void setLine3(String line3) {
		this.line3 = line3;
	}
	public int getNoJursCasesCurr() {
		return noJursCasesCurr;
	}
	public void setNoJursCasesCurr(int noJursCasesCurr) {
		this.noJursCasesCurr = noJursCasesCurr;
	}
	public int getNoJursCasesFrmr() {
		return noJursCasesFrmr;
	}
	public void setNoJursCasesFrmr(int noJursCasesFrmr) {
		this.noJursCasesFrmr = noJursCasesFrmr;
	}
	public int getNoJursCasesNevr() {
		return noJursCasesNevr;
	}
	public void setNoJursCasesNevr(int noJursCasesNevr) {
		this.noJursCasesNevr = noJursCasesNevr;
	}
	public String getCaseType() {
		return caseType;
	}
	public void setCaseType(String caseType) {
		this.caseType = caseType;
	}
	public String getApStatusCd() {
		return apStatusCd;
	}
	public void setApStatusCd(String apStatusCd) {
		this.apStatusCd = apStatusCd;
	}
	public String getOosCaseType() {
		return oosCaseType;
	}
	public void setOosCaseType(String oosCaseType) {
		this.oosCaseType = oosCaseType;
	}
	public String getAfdcCaseNbr() {
		return afdcCaseNbr;
	}
	public void setAfdcCaseNbr(String afdcCaseNbr) {
		this.afdcCaseNbr = afdcCaseNbr;
	}
	public String getStatusChgDate() {
		return statusChgDate;
	}
	public void setStatusChgDate(String statusChgDate) {
		this.statusChgDate = statusChgDate;
	}
	public String getAssistType() {
		return assistType;
	}
	public void setAssistType(String assistType) {
		this.assistType = assistType;
	}
	public String getCaseStartDate() {
		return caseStartDate;
	}
	public void setCaseStartDate(String caseStartDate) {
		this.caseStartDate = caseStartDate;
	}
	public int getInsuOrderedCount() {
		return insuOrderedCount;
	}
	public void setInsuOrderedCount(int insuOrderedCount) {
		this.insuOrderedCount = insuOrderedCount;
	}
	public String getFyStartTimestamp() {
		return fyStartTimestamp;
	}
	public void setFyStartTimestamp(String fyStartTimestamp) {
		this.fyStartTimestamp = fyStartTimestamp;
	}
	public String getFyEndTimestamp() {
		return fyEndTimestamp;
	}
	public void setFyEndTimestamp(String fyEndTimestamp) {
		this.fyEndTimestamp = fyEndTimestamp;
	}
	public String getOldValueCs() {
		return oldValueCs;
	}
	public void setOldValueCs(String oldValueCs) {
		this.oldValueCs = oldValueCs;
	}
	public String getOldCaseStatus() {
		return oldCaseStatus;
	}
	public void setOldCaseStatus(String oldCaseStatus) {
		this.oldCaseStatus = oldCaseStatus;
	}
	public String getOldValueOos() {
		return oldValueOos;
	}
	public void setOldValueOos(String oldValueOos) {
		this.oldValueOos = oldValueOos;
	}
	public String getOldOosType() {
		return oldOosType;
	}
	public void setOldOosType(String oldOosType) {
		this.oldOosType = oldOosType;
	}
	public String getOldRestOos() {
		return oldRestOos;
	}
	public void setOldRestOos(String oldRestOos) {
		this.oldRestOos = oldRestOos;
	}
	public int getTotalCasesRead() {
		return totalCasesRead;
	}
	public void setTotalCasesRead(int totalCasesRead) {
		this.totalCasesRead = totalCasesRead;
	}
	public int getChildAge() {
		return childAge;
	}
	public void setChildAge(int childAge) {
		this.childAge = childAge;
	}
	public String getChildDob() {
		return childDob;
	}
	public void setChildDob(String childDob) {
		this.childDob = childDob;
	}
	public int getChildDobYyyy() {
		return childDobYyyy;
	}
	public void setChildDobYyyy(int childDobYyyy) {
		this.childDobYyyy = childDobYyyy;
	}
	public String getChildDobYm() {
		return childDobYm;
	}
	public void setChildDobYm(String childDobYm) {
		this.childDobYm = childDobYm;
	}
	public int getChildDobMm() {
		return childDobMm;
	}
	public void setChildDobMm(int childDobMm) {
		this.childDobMm = childDobMm;
	}
	public String getChildDobMd() {
		return childDobMd;
	}
	public void setChildDobMd(String childDobMd) {
		this.childDobMd = childDobMd;
	}
	public int getChildDobDd() {
		return childDobDd;
	}
	public void setChildDobDd(int childDobDd) {
		this.childDobDd = childDobDd;
	}
	public String getFlags() {
		return flags;
	}
	public void setFlags(String flags) {
		this.flags = flags;
	}
	public boolean isChildUnderAge18() {
		return childUnderAge18;
	}
	public void setChildUnderAge18(boolean childUnderAge18) {
		this.childUnderAge18 = childUnderAge18;
	}
	public boolean isHearingExists() {
		return hearingExists;
	}
	public void setHearingExists(boolean hearingExists) {
		this.hearingExists = hearingExists;
	}
	public boolean isGrantAmountExists() {
		return grantAmountExists;
	}
	public void setGrantAmountExists(boolean grantAmountExists) {
		this.grantAmountExists = grantAmountExists;
	}
	public boolean isIncludeInLine2() {
		return includeInLine2;
	}
	public void setIncludeInLine2(boolean includeInLine2) {
		this.includeInLine2 = includeInLine2;
	}
	public boolean isIncludeInLine2c() {
		return includeInLine2c;
	}
	public void setIncludeInLine2c(boolean includeInLine2c) {
		this.includeInLine2c = includeInLine2c;
	}
	public boolean isIncludeInLine2d() {
		return includeInLine2d;
	}
	public void setIncludeInLine2d(boolean includeInLine2d) {
		this.includeInLine2d = includeInLine2d;
	}
	public boolean isIncludeInLine3() {
		return includeInLine3;
	}
	public void setIncludeInLine3(boolean includeInLine3) {
		this.includeInLine3 = includeInLine3;
	}
	public boolean isIncludedInLine2() {
		return includedInLine2;
	}
	public void setIncludedInLine2(boolean includedInLine2) {
		this.includedInLine2 = includedInLine2;
	}
	public boolean isIncludedInLine2a() {
		return includedInLine2a;
	}
	public void setIncludedInLine2a(boolean includedInLine2a) {
		this.includedInLine2a = includedInLine2a;
	}
	public boolean isIncludedInLine2b() {
		return includedInLine2b;
	}
	public void setIncludedInLine2b(boolean includedInLine2b) {
		this.includedInLine2b = includedInLine2b;
	}
	public boolean isIncludedInLine2c() {
		return includedInLine2c;
	}
	public void setIncludedInLine2c(boolean includedInLine2c) {
		this.includedInLine2c = includedInLine2c;
	}
	public boolean isIncludedInLine2d() {
		return includedInLine2d;
	}
	public void setIncludedInLine2d(boolean includedInLine2d) {
		this.includedInLine2d = includedInLine2d;
	}
	public boolean isIncludedInLine2e() {
		return includedInLine2e;
	}
	public void setIncludedInLine2e(boolean includedInLine2e) {
		this.includedInLine2e = includedInLine2e;
	}
	public boolean isIncludedInLine2h() {
		return includedInLine2h;
	}
	public void setIncludedInLine2h(boolean includedInLine2h) {
		this.includedInLine2h = includedInLine2h;
	}
	public boolean isIncludedInLine2i() {
		return includedInLine2i;
	}
	public void setIncludedInLine2i(boolean includedInLine2i) {
		this.includedInLine2i = includedInLine2i;
	}
	public Double getChSupArrs() {
		return chSupArrs;
	}
	public void setChSupArrs(Double chSupArrs) {
		this.chSupArrs = chSupArrs;
	}
	public Double getMedSupArrs() {
		return medSupArrs;
	}
	public void setMedSupArrs(Double medSupArrs) {
		this.medSupArrs = medSupArrs;
	}
	public String getStartDate() {
		return startDate;
	}
	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}
	public String getEndDate() {
		return endDate;
	}
	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}
	public String getGrantStart() {
		return grantStart;
	}
	public void setGrantStart(String grantStart) {
		this.grantStart = grantStart;
	}
	public int getMonthsActive() {
		return monthsActive;
	}
	public void setMonthsActive(int monthsActive) {
		this.monthsActive = monthsActive;
	}
	public String getCalcStart() {
		return calcStart;
	}
	public void setCalcStart(String calcStart) {
		this.calcStart = calcStart;
	}
	public String getCalcStartYyyy() {
		return calcStartYyyy;
	}
	public void setCalcStartYyyy(String calcStartYyyy) {
		this.calcStartYyyy = calcStartYyyy;
	}
	public int getCalcStartYyyyn() {
		return calcStartYyyyn;
	}
	public void setCalcStartYyyyn(int calcStartYyyyn) {
		this.calcStartYyyyn = calcStartYyyyn;
	}
	public String getCsYm() {
		return csYm;
	}
	public void setCsYm(String csYm) {
		this.csYm = csYm;
	}
	public String getCalcStartMm() {
		return calcStartMm;
	}
	public void setCalcStartMm(String calcStartMm) {
		this.calcStartMm = calcStartMm;
	}
	public int getCalcStartMmn() {
		return calcStartMmn;
	}
	public void setCalcStartMmn(int calcStartMmn) {
		this.calcStartMmn = calcStartMmn;
	}
	public String getCsMn() {
		return csMn;
	}
	public void setCsMn(String csMn) {
		this.csMn = csMn;
	}
	public String getCalcStartDd() {
		return calcStartDd;
	}
	public void setCalcStartDd(String calcStartDd) {
		this.calcStartDd = calcStartDd;
	}
	public String getCalcEnd() {
		return calcEnd;
	}
	public void setCalcEnd(String calcEnd) {
		this.calcEnd = calcEnd;
	}
	public String getCalcEndYyyy() {
		return calcEndYyyy;
	}
	public void setCalcEndYyyy(String calcEndYyyy) {
		this.calcEndYyyy = calcEndYyyy;
	}
	public int getCalcEndYyyyn() {
		return calcEndYyyyn;
	}
	public void setCalcEndYyyyn(int calcEndYyyyn) {
		this.calcEndYyyyn = calcEndYyyyn;
	}
	public String getCeYm() {
		return ceYm;
	}
	public void setCeYm(String ceYm) {
		this.ceYm = ceYm;
	}
	public String getCalcEndMm() {
		return calcEndMm;
	}
	public void setCalcEndMm(String calcEndMm) {
		this.calcEndMm = calcEndMm;
	}
	public int getCalcEndMmn() {
		return calcEndMmn;
	}
	public void setCalcEndMmn(int calcEndMmn) {
		this.calcEndMmn = calcEndMmn;
	}
	public String getCeMn() {
		return ceMn;
	}
	public void setCeMn(String ceMn) {
		this.ceMn = ceMn;
	}
	public String getCalcEndDd() {
		return calcEndDd;
	}
	public void setCalcEndDd(String calcEndDd) {
		this.calcEndDd = calcEndDd;
	}
	public String getSept() {
		return sept;
	}
	public void setSept(String sept) {
		this.sept = sept;
	}
	public String getSeptYyyy() {
		return septYyyy;
	}
	public void setSeptYyyy(String septYyyy) {
		this.septYyyy = septYyyy;
	}
	public String getsYm() {
		return sYm;
	}
	public void setsYm(String sYm) {
		this.sYm = sYm;
	}
	public String getSeptMm() {
		return septMm;
	}
	public void setSeptMm(String septMm) {
		this.septMm = septMm;
	}
	public String getsMn() {
		return sMn;
	}
	public void setsMn(String sMn) {
		this.sMn = sMn;
	}
	public String getSeptDd() {
		return septDd;
	}
	public void setSeptDd(String septDd) {
		this.septDd = septDd;
	}
	public boolean isObligationExists() {
		return obligationExists;
	}
	public void setObligationExists(boolean obligationExists) {
		this.obligationExists = obligationExists;
	}
	public boolean isNotOnly() {
		return notOnly;
	}
	public void setNotOnly(boolean notOnly) {
		this.notOnly = notOnly;
	}
	public boolean isMoved() {
		return moved;
	}
	public void setMoved(boolean moved) {
		this.moved = moved;
	}
	public int getExists() {
		return exists;
	}
	public void setExists(int exists) {
		this.exists = exists;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	public Double getTotAArrsDue() {
		return totAArrsDue;
	}
	public void setTotAArrsDue(Double totAArrsDue) {
		this.totAArrsDue = totAArrsDue;
	}
	public Double getTotAArrsRcvd() {
		return totAArrsRcvd;
	}
	public void setTotAArrsRcvd(Double totAArrsRcvd) {
		this.totAArrsRcvd = totAArrsRcvd;
	}
	public Double getTotNArrsDue() {
		return totNArrsDue;
	}
	public void setTotNArrsDue(Double totNArrsDue) {
		this.totNArrsDue = totNArrsDue;
	}
	public Double getTotNArrsRcvd() {
		return totNArrsRcvd;
	}
	public void setTotNArrsRcvd(Double totNArrsRcvd) {
		this.totNArrsRcvd = totNArrsRcvd;
	}
	public Double getAfdcChSupDelq() {
		return afdcChSupDelq;
	}
	public void setAfdcChSupDelq(Double afdcChSupDelq) {
		this.afdcChSupDelq = afdcChSupDelq;
	}
	public Double getAfdcChSupInGrace() {
		return afdcChSupInGrace;
	}
	public void setAfdcChSupInGrace(Double afdcChSupInGrace) {
		this.afdcChSupInGrace = afdcChSupInGrace;
	}
	public Double getAfdcMedDue() {
		return afdcMedDue;
	}
	public void setAfdcMedDue(Double afdcMedDue) {
		this.afdcMedDue = afdcMedDue;
	}
	public Double getAfdcMedRcvd() {
		return afdcMedRcvd;
	}
	public void setAfdcMedRcvd(Double afdcMedRcvd) {
		this.afdcMedRcvd = afdcMedRcvd;
	}
	public Double getAfdcMdSupDelq() {
		return afdcMdSupDelq;
	}
	public void setAfdcMdSupDelq(Double afdcMdSupDelq) {
		this.afdcMdSupDelq = afdcMdSupDelq;
	}
	public Double getAfdcMdSupInGrace() {
		return afdcMdSupInGrace;
	}
	public void setAfdcMdSupInGrace(Double afdcMdSupInGrace) {
		this.afdcMdSupInGrace = afdcMdSupInGrace;
	}
	public Double getNafdcChSupDelq() {
		return nafdcChSupDelq;
	}
	public void setNafdcChSupDelq(Double nafdcChSupDelq) {
		this.nafdcChSupDelq = nafdcChSupDelq;
	}
	public Double getNafdcChSupInGrace() {
		return nafdcChSupInGrace;
	}
	public void setNafdcChSupInGrace(Double nafdcChSupInGrace) {
		this.nafdcChSupInGrace = nafdcChSupInGrace;
	}
	public Double getNafdcMedDue() {
		return nafdcMedDue;
	}
	public void setNafdcMedDue(Double nafdcMedDue) {
		this.nafdcMedDue = nafdcMedDue;
	}
	public Double getNafdcMedRcvd() {
		return nafdcMedRcvd;
	}
	public void setNafdcMedRcvd(Double nafdcMedRcvd) {
		this.nafdcMedRcvd = nafdcMedRcvd;
	}
	public Double getNafdcMdSupDelq() {
		return nafdcMdSupDelq;
	}
	public void setNafdcMdSupDelq(Double nafdcMdSupDelq) {
		this.nafdcMdSupDelq = nafdcMdSupDelq;
	}
	public Double getNafdcMdSupInGrace() {
		return nafdcMdSupInGrace;
	}
	public void setNafdcMdSupInGrace(Double nafdcMdSupInGrace) {
		this.nafdcMdSupInGrace = nafdcMdSupInGrace;
	}
	public Double getTotACsDelqRcvd() {
		return totACsDelqRcvd;
	}
	public void setTotACsDelqRcvd(Double totACsDelqRcvd) {
		this.totACsDelqRcvd = totACsDelqRcvd;
	}
	public Double getTotNCsDelqRcvd() {
		return totNCsDelqRcvd;
	}
	public void setTotNCsDelqRcvd(Double totNCsDelqRcvd) {
		this.totNCsDelqRcvd = totNCsDelqRcvd;
	}
	public Double getTotAMsDelqRcvd() {
		return totAMsDelqRcvd;
	}
	public void setTotAMsDelqRcvd(Double totAMsDelqRcvd) {
		this.totAMsDelqRcvd = totAMsDelqRcvd;
	}
	public Double getTotNMsDelqRcvd() {
		return totNMsDelqRcvd;
	}
	public void setTotNMsDelqRcvd(Double totNMsDelqRcvd) {
		this.totNMsDelqRcvd = totNMsDelqRcvd;
	}
	public Double getaCsInGraceRcvd() {
		return aCsInGraceRcvd;
	}
	public void setaCsInGraceRcvd(Double aCsInGraceRcvd) {
		this.aCsInGraceRcvd = aCsInGraceRcvd;
	}
	public Double getnCsInGraceRcvd() {
		return nCsInGraceRcvd;
	}
	public void setnCsInGraceRcvd(Double nCsInGraceRcvd) {
		this.nCsInGraceRcvd = nCsInGraceRcvd;
	}
	public Double getaMsInGraceRcvd() {
		return aMsInGraceRcvd;
	}
	public void setaMsInGraceRcvd(Double aMsInGraceRcvd) {
		this.aMsInGraceRcvd = aMsInGraceRcvd;
	}
	public Double getnMsInGraceRcvd() {
		return nMsInGraceRcvd;
	}
	public void setnMsInGraceRcvd(Double nMsInGraceRcvd) {
		this.nMsInGraceRcvd = nMsInGraceRcvd;
	}
	public Double getTotNArrsCint() {
		return totNArrsCint;
	}
	public void setTotNArrsCint(Double totNArrsCint) {
		this.totNArrsCint = totNArrsCint;
	}
	public Double getTotNArrsSint() {
		return totNArrsSint;
	}
	public void setTotNArrsSint(Double totNArrsSint) {
		this.totNArrsSint = totNArrsSint;
	}
	public Double getMthNArrsCint() {
		return mthNArrsCint;
	}
	public void setMthNArrsCint(Double mthNArrsCint) {
		this.mthNArrsCint = mthNArrsCint;
	}
	public Double getTotNMedCint() {
		return totNMedCint;
	}
	public void setTotNMedCint(Double totNMedCint) {
		this.totNMedCint = totNMedCint;
	}
	public Double getTotNMedSint() {
		return totNMedSint;
	}
	public void setTotNMedSint(Double totNMedSint) {
		this.totNMedSint = totNMedSint;
	}
	public Double getMthNMedCint() {
		return mthNMedCint;
	}
	public void setMthNMedCint(Double mthNMedCint) {
		this.mthNMedCint = mthNMedCint;
	}
	public Double getTcArsDue() {
		return tcArsDue;
	}
	public void setTcArsDue(Double tcArsDue) {
		this.tcArsDue = tcArsDue;
	}
	public Double getTcArsRcv() {
		return tcArsRcv;
	}
	public void setTcArsRcv(Double tcArsRcv) {
		this.tcArsRcv = tcArsRcv;
	}
	public Double getTcChSupDel() {
		return tcChSupDel;
	}
	public void setTcChSupDel(Double tcChSupDel) {
		this.tcChSupDel = tcChSupDel;
	}
	public Double getTcCsDelRcv() {
		return tcCsDelRcv;
	}
	public void setTcCsDelRcv(Double tcCsDelRcv) {
		this.tcCsDelRcv = tcCsDelRcv;
	}
	public Double getuArsDue() {
		return uArsDue;
	}
	public void setuArsDue(Double uArsDue) {
		this.uArsDue = uArsDue;
	}
	public Double getuArsRcv() {
		return uArsRcv;
	}
	public void setuArsRcv(Double uArsRcv) {
		this.uArsRcv = uArsRcv;
	}
	public Double getuChSupDel() {
		return uChSupDel;
	}
	public void setuChSupDel(Double uChSupDel) {
		this.uChSupDel = uChSupDel;
	}
	public Double getuCsDelRcv() {
		return uCsDelRcv;
	}
	public void setuCsDelRcv(Double uCsDelRcv) {
		this.uCsDelRcv = uCsDelRcv;
	}
	public Double getnArsCintRcv() {
		return nArsCintRcv;
	}
	public void setnArsCintRcv(Double nArsCintRcv) {
		this.nArsCintRcv = nArsCintRcv;
	}
	public Double getnArsSintRcv() {
		return nArsSintRcv;
	}
	public void setnArsSintRcv(Double nArsSintRcv) {
		this.nArsSintRcv = nArsSintRcv;
	}
	public Double getMthNArsIntRcv() {
		return mthNArsIntRcv;
	}
	public void setMthNArsIntRcv(Double mthNArsIntRcv) {
		this.mthNArsIntRcv = mthNArsIntRcv;
	}
	public Double getTcArsCint() {
		return tcArsCint;
	}
	public void setTcArsCint(Double tcArsCint) {
		this.tcArsCint = tcArsCint;
	}
	public Double getTcArsCintRcv() {
		return tcArsCintRcv;
	}
	public void setTcArsCintRcv(Double tcArsCintRcv) {
		this.tcArsCintRcv = tcArsCintRcv;
	}
	public Double getTcArsSint() {
		return tcArsSint;
	}
	public void setTcArsSint(Double tcArsSint) {
		this.tcArsSint = tcArsSint;
	}
	public Double getTcArsSintRcv() {
		return tcArsSintRcv;
	}
	public void setTcArsSintRcv(Double tcArsSintRcv) {
		this.tcArsSintRcv = tcArsSintRcv;
	}
	public Double getMthTcArsInt() {
		return mthTcArsInt;
	}
	public void setMthTcArsInt(Double mthTcArsInt) {
		this.mthTcArsInt = mthTcArsInt;
	}
	public Double getMthTcArsIntRcv() {
		return mthTcArsIntRcv;
	}
	public void setMthTcArsIntRcv(Double mthTcArsIntRcv) {
		this.mthTcArsIntRcv = mthTcArsIntRcv;
	}
	public Double getuArsCint() {
		return uArsCint;
	}
	public void setuArsCint(Double uArsCint) {
		this.uArsCint = uArsCint;
	}
	public Double getuArsCintRcv() {
		return uArsCintRcv;
	}
	public void setuArsCintRcv(Double uArsCintRcv) {
		this.uArsCintRcv = uArsCintRcv;
	}
	public Double getuArsSint() {
		return uArsSint;
	}
	public void setuArsSint(Double uArsSint) {
		this.uArsSint = uArsSint;
	}
	public Double getuArsSintRcv() {
		return uArsSintRcv;
	}
	public void setuArsSintRcv(Double uArsSintRcv) {
		this.uArsSintRcv = uArsSintRcv;
	}
	public Double getMthUArsInt() {
		return mthUArsInt;
	}
	public void setMthUArsInt(Double mthUArsInt) {
		this.mthUArsInt = mthUArsInt;
	}
	public Double getMthUArsIntRcv() {
		return mthUArsIntRcv;
	}
	public void setMthUArsIntRcv(Double mthUArsIntRcv) {
		this.mthUArsIntRcv = mthUArsIntRcv;
	}
	public Double getTcChSupInGrace() {
		return tcChSupInGrace;
	}
	public void setTcChSupInGrace(Double tcChSupInGrace) {
		this.tcChSupInGrace = tcChSupInGrace;
	}
	public Double getTcCsInGraceRcv() {
		return tcCsInGraceRcv;
	}
	public void setTcCsInGraceRcv(Double tcCsInGraceRcv) {
		this.tcCsInGraceRcv = tcCsInGraceRcv;
	}
	public Double getuChSupInGrace() {
		return uChSupInGrace;
	}
	public void setuChSupInGrace(Double uChSupInGrace) {
		this.uChSupInGrace = uChSupInGrace;
	}
	public Double getuCsInGraceRcv() {
		return uCsInGraceRcv;
	}
	public void setuCsInGraceRcv(Double uCsInGraceRcv) {
		this.uCsInGraceRcv = uCsInGraceRcv;
	}
	public Double getnMedCintRcv() {
		return nMedCintRcv;
	}
	public void setnMedCintRcv(Double nMedCintRcv) {
		this.nMedCintRcv = nMedCintRcv;
	}
	public Double getnMedSintRcv() {
		return nMedSintRcv;
	}
	public void setnMedSintRcv(Double nMedSintRcv) {
		this.nMedSintRcv = nMedSintRcv;
	}
	public Double getMthNMedIntRcv() {
		return mthNMedIntRcv;
	}
	public void setMthNMedIntRcv(Double mthNMedIntRcv) {
		this.mthNMedIntRcv = mthNMedIntRcv;
	}
	public String getFyStart() {
		return fyStart;
	}
	public void setFyStart(String fyStart) {
		this.fyStart = fyStart;
	}
	public String getFysYyyy() {
		return fysYyyy;
	}
	public void setFysYyyy(String fysYyyy) {
		this.fysYyyy = fysYyyy;
	}
	public String getFysYm() {
		return fysYm;
	}
	public void setFysYm(String fysYm) {
		this.fysYm = fysYm;
	}
	public String getFysMm() {
		return fysMm;
	}
	public void setFysMm(String fysMm) {
		this.fysMm = fysMm;
	}
	public String getFysMd() {
		return fysMd;
	}
	public void setFysMd(String fysMd) {
		this.fysMd = fysMd;
	}
	public String getFysDd() {
		return fysDd;
	}
	public void setFysDd(String fysDd) {
		this.fysDd = fysDd;
	}
	public String getFyEnd() {
		return fyEnd;
	}
	public void setFyEnd(String fyEnd) {
		this.fyEnd = fyEnd;
	}
	public String getFyeYyyy() {
		return fyeYyyy;
	}
	public void setFyeYyyy(String fyeYyyy) {
		this.fyeYyyy = fyeYyyy;
	}
	public String getFyeYm() {
		return fyeYm;
	}
	public void setFyeYm(String fyeYm) {
		this.fyeYm = fyeYm;
	}
	public String getFyeMm() {
		return fyeMm;
	}
	public void setFyeMm(String fyeMm) {
		this.fyeMm = fyeMm;
	}
	public String getFyeMd() {
		return fyeMd;
	}
	public void setFyeMd(String fyeMd) {
		this.fyeMd = fyeMd;
	}
	public String getFyeDd() {
		return fyeDd;
	}
	public void setFyeDd(String fyeDd) {
		this.fyeDd = fyeDd;
	}
	public int getFyQtr() {
		return fyQtr;
	}
	public void setFyQtr(int fyQtr) {
		this.fyQtr = fyQtr;
	}
	public String getWork() {
		return work;
	}
	public void setWork(String work) {
		this.work = work;
	}
	public String getCaseIda() {
		return caseIda;
	}
	public void setCaseIda(String caseIda) {
		this.caseIda = caseIda;
	}
	public int getCaseId() {
		return caseId;
	}
	public void setCaseId(int caseId) {
		this.caseId = caseId;
	}
	public String getCdn() {
		return cdn;
	}
	public void setCdn(String cdn) {
		this.cdn = cdn;
	}
	public String getCdn9() {
		return cdn9;
	}
	public void setCdn9(String cdn9) {
		this.cdn9 = cdn9;
	}
	public String getCdn2() {
		return cdn2;
	}
	public void setCdn2(String cdn2) {
		this.cdn2 = cdn2;
	}
	public int getCnt() {
		return cnt;
	}
	public void setCnt(int cnt) {
		this.cnt = cnt;
	}
	public int getOblgCnt() {
		return oblgCnt;
	}
	public void setOblgCnt(int oblgCnt) {
		this.oblgCnt = oblgCnt;
	}
	public String getOblgType() {
		return oblgType;
	}
	public void setOblgType(String oblgType) {
		this.oblgType = oblgType;
	}
	public String getOldValue() {
		return oldValue;
	}
	public void setOldValue(String oldValue) {
		this.oldValue = oldValue;
	}
	public String getOldCaseType() {
		return oldCaseType;
	}
	public void setOldCaseType(String oldCaseType) {
		this.oldCaseType = oldCaseType;
	}
	public String getOldRes2() {
		return oldRes2;
	}
	public void setOldRes2(String oldRes2) {
		this.oldRes2 = oldRes2;
	}
	public String getNewValue() {
		return newValue;
	}
	public void setNewValue(String newValue) {
		this.newValue = newValue;
	}
	public String getNewCaseType() {
		return newCaseType;
	}
	public void setNewCaseType(String newCaseType) {
		this.newCaseType = newCaseType;
	}
	public String getNewTypeDate() {
		return newTypeDate;
	}
	public void setNewTypeDate(String newTypeDate) {
		this.newTypeDate = newTypeDate;
	}
	public String getNewRest2() {
		return newRest2;
	}
	public void setNewRest2(String newRest2) {
		this.newRest2 = newRest2;
	}
	public Double getAmount() {
		return amount;
	}
	public void setAmount(Double amount) {
		this.amount = amount;
	}
	public String getObligationType() {
		return obligationType;
	}
	public void setObligationType(String obligationType) {
		this.obligationType = obligationType;
	}
	public String getOrderType() {
		return orderType;
	}
	public void setOrderType(String orderType) {
		this.orderType = orderType;
	}
	public String getCsExtend18() {
		return csExtend18;
	}
	public void setCsExtend18(String csExtend18) {
		this.csExtend18 = csExtend18;
	}
	public String getServiceType() {
		return serviceType;
	}
	public void setServiceType(String serviceType) {
		this.serviceType = serviceType;
	}
	public String getApCountry() {
		return apCountry;
	}
	public void setApCountry(String apCountry) {
		this.apCountry = apCountry;
	}
	public String getCtCountry() {
		return ctCountry;
	}
	public void setCtCountry(String ctCountry) {
		this.ctCountry = ctCountry;
	}
	public Date getDateVar() {
		return dateVar;
	}
	public void setDateVar(Date dateVar) {
		this.dateVar = dateVar;
	}
	public Date getDateVar2() {
		return dateVar2;
	}
	public void setDateVar2(Date dateVar2) {
		this.dateVar2 = dateVar2;
	}
	public int getPagenumber() {
		return pagenumber;
	}
	public void setPagenumber(int pagenumber) {
		this.pagenumber = pagenumber;
	}
	public String getChangedTime() {
		return changedTime;
	}
	public void setChangedTime(String changedTime) {
		this.changedTime = changedTime;
	}
	public String getTimeOfEvent() {
		return timeOfEvent;
	}
	public void setTimeOfEvent(String timeOfEvent) {
		this.timeOfEvent = timeOfEvent;
	}
	public String getCommitData() {
		return commitData;
	}
	public void setCommitData(String commitData) {
		this.commitData = commitData;
	}
	public int getNbrOfTables() {
		return nbrOfTables;
	}
	public void setNbrOfTables(int nbrOfTables) {
		this.nbrOfTables = nbrOfTables;
	}
	public List<String> getViewArray() {
		return viewArray;
	}
	public void setViewArray(List<String> viewArray) {
		this.viewArray = viewArray;
	}
	public String getRespFips() {
		return respFips;
	}
	public void setRespFips(String respFips) {
		this.respFips = respFips;
	}
	public String getInitFips() {
		return initFips;
	}
	public void setInitFips(String initFips) {
		this.initFips = initFips;
	}
	public String getMthOrQtr() {
		return mthOrQtr;
	}
	public void setMthOrQtr(String mthOrQtr) {
		this.mthOrQtr = mthOrQtr;
	}
	public String getFiscalYear() {
		return fiscalYear;
	}
	public void setFiscalYear(String fiscalYear) {
		this.fiscalYear = fiscalYear;
	}
	public String getWeo2p57aCnt() {
		return weo2p57aCnt;
	}
	public void setWeo2p57aCnt(String weo2p57aCnt) {
		this.weo2p57aCnt = weo2p57aCnt;
	}
	public String getgApPin() {
		return gApPin;
	}
	public void setgApPin(String gApPin) {
		this.gApPin = gApPin;
	}
	public String getgCtPin() {
		return gCtPin;
	}
	public void setgCtPin(String gCtPin) {
		this.gCtPin = gCtPin;
	}
	public String getWeo2p57aCaseId() {
		return weo2p57aCaseId;
	}
	public void setWeo2p57aCaseId(String weo2p57aCaseId) {
		this.weo2p57aCaseId = weo2p57aCaseId;
	}
	public String getWeo2p57aCaseType() {
		return weo2p57aCaseType;
	}
	public void setWeo2p57aCaseType(String weo2p57aCaseType) {
		this.weo2p57aCaseType = weo2p57aCaseType;
	}
	public String getWeo2p57aStatus() {
		return weo2p57aStatus;
	}
	public void setWeo2p57aStatus(String weo2p57aStatus) {
		this.weo2p57aStatus = weo2p57aStatus;
	}
	public String getWeo2p57aCdn() {
		return weo2p57aCdn;
	}
	public void setWeo2p57aCdn(String weo2p57aCdn) {
		this.weo2p57aCdn = weo2p57aCdn;
	}
	public String getWeo2p57aApStatusCd() {
		return weo2p57aApStatusCd;
	}
	public void setWeo2p57aApStatusCd(String weo2p57aApStatusCd) {
		this.weo2p57aApStatusCd = weo2p57aApStatusCd;
	}
	public String getWeo2p57aOosCaseType() {
		return weo2p57aOosCaseType;
	}
	public void setWeo2p57aOosCaseType(String weo2p57aOosCaseType) {
		this.weo2p57aOosCaseType = weo2p57aOosCaseType;
	}
	public String getWeo2p57aAfdcCaseNbr() {
		return weo2p57aAfdcCaseNbr;
	}
	public void setWeo2p57aAfdcCaseNbr(String weo2p57aAfdcCaseNbr) {
		this.weo2p57aAfdcCaseNbr = weo2p57aAfdcCaseNbr;
	}
	public String getWeo2p57aCaseStartDate() {
		return weo2p57aCaseStartDate;
	}
	public void setWeo2p57aCaseStartDate(String weo2p57aCaseStartDate) {
		this.weo2p57aCaseStartDate = weo2p57aCaseStartDate;
	}
	public String getWeo2p57aAssistType() {
		return weo2p57aAssistType;
	}
	public void setWeo2p57aAssistType(String weo2p57aAssistType) {
		this.weo2p57aAssistType = weo2p57aAssistType;
	}
	public String getWeo2p57aStatusChgDate() {
		return weo2p57aStatusChgDate;
	}
	public void setWeo2p57aStatusChgDate(String weo2p57aStatusChgDate) {
		this.weo2p57aStatusChgDate = weo2p57aStatusChgDate;
	}
	public String getWeo2p57aServiceType() {
		return weo2p57aServiceType;
	}
	public void setWeo2p57aServiceType(String weo2p57aServiceType) {
		this.weo2p57aServiceType = weo2p57aServiceType;
	}
	public String getWeo2p57aGApPin() {
		return weo2p57aGApPin;
	}
	public void setWeo2p57aGApPin(String weo2p57aGApPin) {
		this.weo2p57aGApPin = weo2p57aGApPin;
	}
	public String getWeo2p57aGCtPin() {
		return weo2p57aGCtPin;
	}
	public void setWeo2p57aGCtPin(String weo2p57aGCtPin) {
		this.weo2p57aGCtPin = weo2p57aGCtPin;
	}
	public String getWeo2p57aApCountry() {
		return weo2p57aApCountry;
	}
	public void setWeo2p57aApCountry(String weo2p57aApCountry) {
		this.weo2p57aApCountry = weo2p57aApCountry;
	}
	public String getWeo2p57aCtCountry() {
		return weo2p57aCtCountry;
	}
	public void setWeo2p57aCtCountry(String weo2p57aCtCountry) {
		this.weo2p57aCtCountry = weo2p57aCtCountry;
	}
	public String getWeo2p57aAmount() {
		return weo2p57aAmount;
	}
	public void setWeo2p57aAmount(String weo2p57aAmount) {
		this.weo2p57aAmount = weo2p57aAmount;
	}
	public String getWeo2p57aStartDate() {
		return weo2p57aStartDate;
	}
	public void setWeo2p57aStartDate(String weo2p57aStartDate) {
		this.weo2p57aStartDate = weo2p57aStartDate;
	}
	public String getWeo2p57aEndDate() {
		return weo2p57aEndDate;
	}
	public void setWeo2p57aEndDate(String weo2p57aEndDate) {
		this.weo2p57aEndDate = weo2p57aEndDate;
	}
	public String getWeo2p57aObligationType() {
		return weo2p57aObligationType;
	}
	public void setWeo2p57aObligationType(String weo2p57aObligationType) {
		this.weo2p57aObligationType = weo2p57aObligationType;
	}
	public String getWeo2p57aOrderType() {
		return weo2p57aOrderType;
	}
	public void setWeo2p57aOrderType(String weo2p57aOrderType) {
		this.weo2p57aOrderType = weo2p57aOrderType;
	}
	public String getWeo2p57aCsExtend18() {
		return weo2p57aCsExtend18;
	}
	public void setWeo2p57aCsExtend18(String weo2p57aCsExtend18) {
		this.weo2p57aCsExtend18 = weo2p57aCsExtend18;
	}
	public String getWeo2p57aRespFips() {
		return weo2p57aRespFips;
	}
	public void setWeo2p57aRespFips(String weo2p57aRespFips) {
		this.weo2p57aRespFips = weo2p57aRespFips;
	}
	public String getWeo2p57aInitFips() {
		return weo2p57aInitFips;
	}
	public void setWeo2p57aInitFips(String weo2p57aInitFips) {
		this.weo2p57aInitFips = weo2p57aInitFips;
	}
	public String getWeo2p57aAfdcChSupDelq() {
		return weo2p57aAfdcChSupDelq;
	}
	public void setWeo2p57aAfdcChSupDelq(String weo2p57aAfdcChSupDelq) {
		this.weo2p57aAfdcChSupDelq = weo2p57aAfdcChSupDelq;
	}
	public String getWeo2p57aAfdcChSupInGrace() {
		return weo2p57aAfdcChSupInGrace;
	}
	public void setWeo2p57aAfdcChSupInGrace(String weo2p57aAfdcChSupInGrace) {
		this.weo2p57aAfdcChSupInGrace = weo2p57aAfdcChSupInGrace;
	}
	public String getWeo2p57aAfdcMedDue() {
		return weo2p57aAfdcMedDue;
	}
	public void setWeo2p57aAfdcMedDue(String weo2p57aAfdcMedDue) {
		this.weo2p57aAfdcMedDue = weo2p57aAfdcMedDue;
	}
	public String getWeo2p57aAfdcMedRcvd() {
		return weo2p57aAfdcMedRcvd;
	}
	public void setWeo2p57aAfdcMedRcvd(String weo2p57aAfdcMedRcvd) {
		this.weo2p57aAfdcMedRcvd = weo2p57aAfdcMedRcvd;
	}
	public String getWeo2p57aAfdcMdSupDelq() {
		return weo2p57aAfdcMdSupDelq;
	}
	public void setWeo2p57aAfdcMdSupDelq(String weo2p57aAfdcMdSupDelq) {
		this.weo2p57aAfdcMdSupDelq = weo2p57aAfdcMdSupDelq;
	}
	public String getWeo2p57aAfdcMdSupInGrace() {
		return weo2p57aAfdcMdSupInGrace;
	}
	public void setWeo2p57aAfdcMdSupInGrace(String weo2p57aAfdcMdSupInGrace) {
		this.weo2p57aAfdcMdSupInGrace = weo2p57aAfdcMdSupInGrace;
	}
	public String getWeo2p57aNafdcChSupDelq() {
		return weo2p57aNafdcChSupDelq;
	}
	public void setWeo2p57aNafdcChSupDelq(String weo2p57aNafdcChSupDelq) {
		this.weo2p57aNafdcChSupDelq = weo2p57aNafdcChSupDelq;
	}
	public String getWeo2p57aNafdcChSupInGrace() {
		return weo2p57aNafdcChSupInGrace;
	}
	public void setWeo2p57aNafdcChSupInGrace(String weo2p57aNafdcChSupInGrace) {
		this.weo2p57aNafdcChSupInGrace = weo2p57aNafdcChSupInGrace;
	}
	public String getWeo2p57aNafdcMedDue() {
		return weo2p57aNafdcMedDue;
	}
	public void setWeo2p57aNafdcMedDue(String weo2p57aNafdcMedDue) {
		this.weo2p57aNafdcMedDue = weo2p57aNafdcMedDue;
	}
	public String getWeo2p57aNafdcMedRcvd() {
		return weo2p57aNafdcMedRcvd;
	}
	public void setWeo2p57aNafdcMedRcvd(String weo2p57aNafdcMedRcvd) {
		this.weo2p57aNafdcMedRcvd = weo2p57aNafdcMedRcvd;
	}
	public String getWeo2p57aNafdcMdSupDelq() {
		return weo2p57aNafdcMdSupDelq;
	}
	public void setWeo2p57aNafdcMdSupDelq(String weo2p57aNafdcMdSupDelq) {
		this.weo2p57aNafdcMdSupDelq = weo2p57aNafdcMdSupDelq;
	}
	public String getWeo2p57aNafdcMdSupInGrace() {
		return weo2p57aNafdcMdSupInGrace;
	}
	public void setWeo2p57aNafdcMdSupInGrace(String weo2p57aNafdcMdSupInGrace) {
		this.weo2p57aNafdcMdSupInGrace = weo2p57aNafdcMdSupInGrace;
	}
	public String getWeo2p57aTotACsDelqRcvd() {
		return weo2p57aTotACsDelqRcvd;
	}
	public void setWeo2p57aTotACsDelqRcvd(String weo2p57aTotACsDelqRcvd) {
		this.weo2p57aTotACsDelqRcvd = weo2p57aTotACsDelqRcvd;
	}
	public String getWeo2p57aTotAMsDelqRcvd() {
		return weo2p57aTotAMsDelqRcvd;
	}
	public void setWeo2p57aTotAMsDelqRcvd(String weo2p57aTotAMsDelqRcvd) {
		this.weo2p57aTotAMsDelqRcvd = weo2p57aTotAMsDelqRcvd;
	}
	public String getWeo2p57aACsInGraceRcvd() {
		return weo2p57aACsInGraceRcvd;
	}
	public void setWeo2p57aACsInGraceRcvd(String weo2p57aACsInGraceRcvd) {
		this.weo2p57aACsInGraceRcvd = weo2p57aACsInGraceRcvd;
	}
	public String getWeo2p57aAMsInGraceRcvd() {
		return weo2p57aAMsInGraceRcvd;
	}
	public void setWeo2p57aAMsInGraceRcvd(String weo2p57aAMsInGraceRcvd) {
		this.weo2p57aAMsInGraceRcvd = weo2p57aAMsInGraceRcvd;
	}
	public String getWeo2p57aTotNCsDelqRcvd() {
		return weo2p57aTotNCsDelqRcvd;
	}
	public void setWeo2p57aTotNCsDelqRcvd(String weo2p57aTotNCsDelqRcvd) {
		this.weo2p57aTotNCsDelqRcvd = weo2p57aTotNCsDelqRcvd;
	}
	public String getWeo2p57aTotNMsDelqRcvd() {
		return weo2p57aTotNMsDelqRcvd;
	}
	public void setWeo2p57aTotNMsDelqRcvd(String weo2p57aTotNMsDelqRcvd) {
		this.weo2p57aTotNMsDelqRcvd = weo2p57aTotNMsDelqRcvd;
	}
	public String getWeo2p57aNCsInGraceRcvd() {
		return weo2p57aNCsInGraceRcvd;
	}
	public void setWeo2p57aNCsInGraceRcvd(String weo2p57aNCsInGraceRcvd) {
		this.weo2p57aNCsInGraceRcvd = weo2p57aNCsInGraceRcvd;
	}
	public String getWeo2p57aNMsInGraceRcvd() {
		return weo2p57aNMsInGraceRcvd;
	}
	public void setWeo2p57aNMsInGraceRcvd(String weo2p57aNMsInGraceRcvd) {
		this.weo2p57aNMsInGraceRcvd = weo2p57aNMsInGraceRcvd;
	}
	public String getWeo2p57aTotNArrsCint() {
		return weo2p57aTotNArrsCint;
	}
	public void setWeo2p57aTotNArrsCint(String weo2p57aTotNArrsCint) {
		this.weo2p57aTotNArrsCint = weo2p57aTotNArrsCint;
	}
	public String getWeo2p57aTotNArrsSint() {
		return weo2p57aTotNArrsSint;
	}
	public void setWeo2p57aTotNArrsSint(String weo2p57aTotNArrsSint) {
		this.weo2p57aTotNArrsSint = weo2p57aTotNArrsSint;
	}
	public String getWeo2p57aMthNArrsCint() {
		return weo2p57aMthNArrsCint;
	}
	public void setWeo2p57aMthNArrsCint(String weo2p57aMthNArrsCint) {
		this.weo2p57aMthNArrsCint = weo2p57aMthNArrsCint;
	}
	public String getWeo2p57aTotNMedCint() {
		return weo2p57aTotNMedCint;
	}
	public void setWeo2p57aTotNMedCint(String weo2p57aTotNMedCint) {
		this.weo2p57aTotNMedCint = weo2p57aTotNMedCint;
	}
	public String getWeo2p57aTotNMedSint() {
		return weo2p57aTotNMedSint;
	}
	public void setWeo2p57aTotNMedSint(String weo2p57aTotNMedSint) {
		this.weo2p57aTotNMedSint = weo2p57aTotNMedSint;
	}
	public String getWeo2p57aMthNMedCint() {
		return weo2p57aMthNMedCint;
	}
	public void setWeo2p57aMthNMedCint(String weo2p57aMthNMedCint) {
		this.weo2p57aMthNMedCint = weo2p57aMthNMedCint;
	}
	public String getWeo2p57aTotAArrsDue() {
		return weo2p57aTotAArrsDue;
	}
	public void setWeo2p57aTotAArrsDue(String weo2p57aTotAArrsDue) {
		this.weo2p57aTotAArrsDue = weo2p57aTotAArrsDue;
	}
	public String getWeo2p57aTotAArrsRcvd() {
		return weo2p57aTotAArrsRcvd;
	}
	public void setWeo2p57aTotAArrsRcvd(String weo2p57aTotAArrsRcvd) {
		this.weo2p57aTotAArrsRcvd = weo2p57aTotAArrsRcvd;
	}
	public String getWeo2p57aTotNArrsDue() {
		return weo2p57aTotNArrsDue;
	}
	public void setWeo2p57aTotNArrsDue(String weo2p57aTotNArrsDue) {
		this.weo2p57aTotNArrsDue = weo2p57aTotNArrsDue;
	}
	public String getWeo2p57aTotNArrsRcvd() {
		return weo2p57aTotNArrsRcvd;
	}
	public void setWeo2p57aTotNArrsRcvd(String weo2p57aTotNArrsRcvd) {
		this.weo2p57aTotNArrsRcvd = weo2p57aTotNArrsRcvd;
	}
	public String getWeo2p57aTcArsDue() {
		return weo2p57aTcArsDue;
	}
	public void setWeo2p57aTcArsDue(String weo2p57aTcArsDue) {
		this.weo2p57aTcArsDue = weo2p57aTcArsDue;
	}
	public String getWeo2p57aTcArsRcv() {
		return weo2p57aTcArsRcv;
	}
	public void setWeo2p57aTcArsRcv(String weo2p57aTcArsRcv) {
		this.weo2p57aTcArsRcv = weo2p57aTcArsRcv;
	}
	public String getWeo2p57aTcChSupDel() {
		return weo2p57aTcChSupDel;
	}
	public void setWeo2p57aTcChSupDel(String weo2p57aTcChSupDel) {
		this.weo2p57aTcChSupDel = weo2p57aTcChSupDel;
	}
	public String getWeo2p57aTcCsDelRcv() {
		return weo2p57aTcCsDelRcv;
	}
	public void setWeo2p57aTcCsDelRcv(String weo2p57aTcCsDelRcv) {
		this.weo2p57aTcCsDelRcv = weo2p57aTcCsDelRcv;
	}
	public String getWeo2p57aUArsDue() {
		return weo2p57aUArsDue;
	}
	public void setWeo2p57aUArsDue(String weo2p57aUArsDue) {
		this.weo2p57aUArsDue = weo2p57aUArsDue;
	}
	public String getWeo2p57aUArsRcv() {
		return weo2p57aUArsRcv;
	}
	public void setWeo2p57aUArsRcv(String weo2p57aUArsRcv) {
		this.weo2p57aUArsRcv = weo2p57aUArsRcv;
	}
	public String getWeo2p57aUChSupDel() {
		return weo2p57aUChSupDel;
	}
	public void setWeo2p57aUChSupDel(String weo2p57aUChSupDel) {
		this.weo2p57aUChSupDel = weo2p57aUChSupDel;
	}
	public String getWeo2p57aUCsDelRcv() {
		return weo2p57aUCsDelRcv;
	}
	public void setWeo2p57aUCsDelRcv(String weo2p57aUCsDelRcv) {
		this.weo2p57aUCsDelRcv = weo2p57aUCsDelRcv;
	}
	public String getWeo2p57aNArsCintRcv() {
		return weo2p57aNArsCintRcv;
	}
	public void setWeo2p57aNArsCintRcv(String weo2p57aNArsCintRcv) {
		this.weo2p57aNArsCintRcv = weo2p57aNArsCintRcv;
	}
	public String getWeo2p57aNArsSintRcv() {
		return weo2p57aNArsSintRcv;
	}
	public void setWeo2p57aNArsSintRcv(String weo2p57aNArsSintRcv) {
		this.weo2p57aNArsSintRcv = weo2p57aNArsSintRcv;
	}
	public String getWeo2p57aMthNArsIntRcv() {
		return weo2p57aMthNArsIntRcv;
	}
	public void setWeo2p57aMthNArsIntRcv(String weo2p57aMthNArsIntRcv) {
		this.weo2p57aMthNArsIntRcv = weo2p57aMthNArsIntRcv;
	}
	public String getWeo2p57aTcArsCint() {
		return weo2p57aTcArsCint;
	}
	public void setWeo2p57aTcArsCint(String weo2p57aTcArsCint) {
		this.weo2p57aTcArsCint = weo2p57aTcArsCint;
	}
	public String getWeo2p57aTcArsCintRcv() {
		return weo2p57aTcArsCintRcv;
	}
	public void setWeo2p57aTcArsCintRcv(String weo2p57aTcArsCintRcv) {
		this.weo2p57aTcArsCintRcv = weo2p57aTcArsCintRcv;
	}
	public String getWeo2p57aTcArsSint() {
		return weo2p57aTcArsSint;
	}
	public void setWeo2p57aTcArsSint(String weo2p57aTcArsSint) {
		this.weo2p57aTcArsSint = weo2p57aTcArsSint;
	}
	public String getWeo2p57aTcArsSintRcv() {
		return weo2p57aTcArsSintRcv;
	}
	public void setWeo2p57aTcArsSintRcv(String weo2p57aTcArsSintRcv) {
		this.weo2p57aTcArsSintRcv = weo2p57aTcArsSintRcv;
	}
	public String getWeo2p57aMthTcArsInt() {
		return weo2p57aMthTcArsInt;
	}
	public void setWeo2p57aMthTcArsInt(String weo2p57aMthTcArsInt) {
		this.weo2p57aMthTcArsInt = weo2p57aMthTcArsInt;
	}
	public String getWeo2p57aMthTcArsIntRcv() {
		return weo2p57aMthTcArsIntRcv;
	}
	public void setWeo2p57aMthTcArsIntRcv(String weo2p57aMthTcArsIntRcv) {
		this.weo2p57aMthTcArsIntRcv = weo2p57aMthTcArsIntRcv;
	}
	public String getWeo2p57aUArsCint() {
		return weo2p57aUArsCint;
	}
	public void setWeo2p57aUArsCint(String weo2p57aUArsCint) {
		this.weo2p57aUArsCint = weo2p57aUArsCint;
	}
	public String getWeo2p57aUArsCintRcv() {
		return weo2p57aUArsCintRcv;
	}
	public void setWeo2p57aUArsCintRcv(String weo2p57aUArsCintRcv) {
		this.weo2p57aUArsCintRcv = weo2p57aUArsCintRcv;
	}
	public String getWeo2p57aUArsSint() {
		return weo2p57aUArsSint;
	}
	public void setWeo2p57aUArsSint(String weo2p57aUArsSint) {
		this.weo2p57aUArsSint = weo2p57aUArsSint;
	}
	public String getWeo2p57aUArsSintRcv() {
		return weo2p57aUArsSintRcv;
	}
	public void setWeo2p57aUArsSintRcv(String weo2p57aUArsSintRcv) {
		this.weo2p57aUArsSintRcv = weo2p57aUArsSintRcv;
	}
	public String getWeo2p57aMthUArsInt() {
		return weo2p57aMthUArsInt;
	}
	public void setWeo2p57aMthUArsInt(String weo2p57aMthUArsInt) {
		this.weo2p57aMthUArsInt = weo2p57aMthUArsInt;
	}
	public String getWeo2p57aMthUArsIntRcv() {
		return weo2p57aMthUArsIntRcv;
	}
	public void setWeo2p57aMthUArsIntRcv(String weo2p57aMthUArsIntRcv) {
		this.weo2p57aMthUArsIntRcv = weo2p57aMthUArsIntRcv;
	}
	public String getWeo2p57aTcChSupInGrace() {
		return weo2p57aTcChSupInGrace;
	}
	public void setWeo2p57aTcChSupInGrace(String weo2p57aTcChSupInGrace) {
		this.weo2p57aTcChSupInGrace = weo2p57aTcChSupInGrace;
	}
	public String getWeo2p57aTcCsInGraceRcv() {
		return weo2p57aTcCsInGraceRcv;
	}
	public void setWeo2p57aTcCsInGraceRcv(String weo2p57aTcCsInGraceRcv) {
		this.weo2p57aTcCsInGraceRcv = weo2p57aTcCsInGraceRcv;
	}
	public String getWeo2p57aUChSupInGrace() {
		return weo2p57aUChSupInGrace;
	}
	public void setWeo2p57aUChSupInGrace(String weo2p57aUChSupInGrace) {
		this.weo2p57aUChSupInGrace = weo2p57aUChSupInGrace;
	}
	public String getWeo2p57aUCsInGraceRcv() {
		return weo2p57aUCsInGraceRcv;
	}
	public void setWeo2p57aUCsInGraceRcv(String weo2p57aUCsInGraceRcv) {
		this.weo2p57aUCsInGraceRcv = weo2p57aUCsInGraceRcv;
	}
	public String getWeo2p57aNMedCintRcv() {
		return weo2p57aNMedCintRcv;
	}
	public void setWeo2p57aNMedCintRcv(String weo2p57aNMedCintRcv) {
		this.weo2p57aNMedCintRcv = weo2p57aNMedCintRcv;
	}
	public String getWeo2p57aNMedSintRcv() {
		return weo2p57aNMedSintRcv;
	}
	public void setWeo2p57aNMedSintRcv(String weo2p57aNMedSintRcv) {
		this.weo2p57aNMedSintRcv = weo2p57aNMedSintRcv;
	}
	public String getWeo2p57aMthNMedIntRcv() {
		return weo2p57aMthNMedIntRcv;
	}
	public void setWeo2p57aMthNMedIntRcv(String weo2p57aMthNMedIntRcv) {
		this.weo2p57aMthNMedIntRcv = weo2p57aMthNMedIntRcv;
	}
	public String getWeo2p57aExists() {
		return weo2p57aExists;
	}
	public void setWeo2p57aExists(String weo2p57aExists) {
		this.weo2p57aExists = weo2p57aExists;
	}
	public String getWeo2p57aOldValueCs() {
		return weo2p57aOldValueCs;
	}
	public void setWeo2p57aOldValueCs(String weo2p57aOldValueCs) {
		this.weo2p57aOldValueCs = weo2p57aOldValueCs;
	}
	public String getWeo2p57aTimeOfEvent() {
		return weo2p57aTimeOfEvent;
	}
	public void setWeo2p57aTimeOfEvent(String weo2p57aTimeOfEvent) {
		this.weo2p57aTimeOfEvent = weo2p57aTimeOfEvent;
	}
	public String getWeo2p57aOldValue() {
		return weo2p57aOldValue;
	}
	public void setWeo2p57aOldValue(String weo2p57aOldValue) {
		this.weo2p57aOldValue = weo2p57aOldValue;
	}
	public String getWeo2p57aNewValue() {
		return weo2p57aNewValue;
	}
	public void setWeo2p57aNewValue(String weo2p57aNewValue) {
		this.weo2p57aNewValue = weo2p57aNewValue;
	}
	public String getWeo2p57aOldValueOos() {
		return weo2p57aOldValueOos;
	}
	public void setWeo2p57aOldValueOos(String weo2p57aOldValueOos) {
		this.weo2p57aOldValueOos = weo2p57aOldValueOos;
	}
	public String getWeo2p57aChildDob() {
		return weo2p57aChildDob;
	}
	public void setWeo2p57aChildDob(String weo2p57aChildDob) {
		this.weo2p57aChildDob = weo2p57aChildDob;
	}
	public String getWeo2p57aInsuOrderedCount() {
		return weo2p57aInsuOrderedCount;
	}
	public void setWeo2p57aInsuOrderedCount(String weo2p57aInsuOrderedCount) {
		this.weo2p57aInsuOrderedCount = weo2p57aInsuOrderedCount;
	}
	public String getWeo2p57aGrantStart() {
		return weo2p57aGrantStart;
	}
	public void setWeo2p57aGrantStart(String weo2p57aGrantStart) {
		this.weo2p57aGrantStart = weo2p57aGrantStart;
	}
	public String getWeo2p57aOblgCnt() {
		return weo2p57aOblgCnt;
	}
	public void setWeo2p57aOblgCnt(String weo2p57aOblgCnt) {
		this.weo2p57aOblgCnt = weo2p57aOblgCnt;
	}
	public String getWeo2p57aOblgType() {
		return weo2p57aOblgType;
	}
	public void setWeo2p57aOblgType(String weo2p57aOblgType) {
		this.weo2p57aOblgType = weo2p57aOblgType;
	}
	@Override
	public String toString() {
		return "Weo2p57a [sectionA=" + sectionA + ", line1=" + line1 + ", totCasesCurr=" + totCasesCurr
				+ ", totCasesFrmr=" + totCasesFrmr + ", totCasesNevr=" + totCasesNevr + ", line1a=" + line1a
				+ ", uiCasesCurr=" + uiCasesCurr + ", uiCasesFrmr=" + uiCasesFrmr + ", uiCasesNevr=" + uiCasesNevr
				+ ", line1b=" + line1b + ", urCasesCurr=" + urCasesCurr + ", urCasesFrmr=" + urCasesFrmr
				+ ", urCasesNevr=" + urCasesNevr + ", line1c=" + line1c + ", totMCasesNevr=" + totMCasesNevr
				+ ", line1d=" + line1d + ", trInitCurr=" + trInitCurr + ", trInitFrmr=" + trInitFrmr + ", trInitNevr="
				+ trInitNevr + ", line1e=" + line1e + ", trRecCurr=" + trRecCurr + ", trRecFrmr=" + trRecFrmr
				+ ", trRecNevr=" + trRecNevr + ", line1f=" + line1f + ", interInit=" + interInit + ", line1g=" + line1g
				+ ", interRec=" + interRec + ", line2=" + line2 + ", crtordCasesCurr=" + crtordCasesCurr
				+ ", crtordCasesFrmr=" + crtordCasesFrmr + ", crtordCasesNevr=" + crtordCasesNevr + ", line2a=" + line2a
				+ ", crtordUiCasCurr=" + crtordUiCasCurr + ", crtordUiCasFrmr=" + crtordUiCasFrmr + ", crtordUiCasNevr="
				+ crtordUiCasNevr + ", line2b=" + line2b + ", crtordUrCasCurr=" + crtordUrCasCurr + ", crtordUrCasFrmr="
				+ crtordUrCasFrmr + ", crtordUrCasNevr=" + crtordUrCasNevr + ", line2c=" + line2c + ", zeroOrdCaseCurr="
				+ zeroOrdCaseCurr + ", zeroOrdCaseFrmr=" + zeroOrdCaseFrmr + ", zeroOrdCaseNevr=" + zeroOrdCaseNevr
				+ ", line2d=" + line2d + ", crtordMCasNevr=" + crtordMCasNevr + ", line2e=" + line2e + ", arrsOnlyOrdr="
				+ arrsOnlyOrdr + ", line2f=" + line2f + ", trInitOrdrCurr=" + trInitOrdrCurr + ", trInitOrdrFrmr="
				+ trInitOrdrFrmr + ", trInitOrdrNevr=" + trInitOrdrNevr + ", line2g=" + line2g + ", trRecOrdrCurr="
				+ trRecOrdrCurr + ", trRecOrdrFrmr=" + trRecOrdrFrmr + ", trRecOrdrNevr=" + trRecOrdrNevr + ", line2h="
				+ line2h + ", interInitOrdr=" + interInitOrdr + ", line2i=" + line2i + ", interRecOrdr=" + interRecOrdr
				+ ", line3=" + line3 + ", noJursCasesCurr=" + noJursCasesCurr + ", noJursCasesFrmr=" + noJursCasesFrmr
				+ ", noJursCasesNevr=" + noJursCasesNevr + ", caseType=" + caseType + ", apStatusCd=" + apStatusCd
				+ ", oosCaseType=" + oosCaseType + ", afdcCaseNbr=" + afdcCaseNbr + ", statusChgDate=" + statusChgDate
				+ ", assistType=" + assistType + ", caseStartDate=" + caseStartDate + ", insuOrderedCount="
				+ insuOrderedCount + ", fyStartTimestamp=" + fyStartTimestamp + ", fyEndTimestamp=" + fyEndTimestamp
				+ ", oldValueCs=" + oldValueCs + ", oldCaseStatus=" + oldCaseStatus + ", oldValueOos=" + oldValueOos
				+ ", oldOosType=" + oldOosType + ", oldRestOos=" + oldRestOos + ", totalCasesRead=" + totalCasesRead
				+ ", childAge=" + childAge + ", childDob=" + childDob + ", childDobYyyy=" + childDobYyyy
				+ ", childDobYm=" + childDobYm + ", childDobMm=" + childDobMm + ", childDobMd=" + childDobMd
				+ ", childDobDd=" + childDobDd + ", flags=" + flags + ", childUnderAge18=" + childUnderAge18
				+ ", hearingExists=" + hearingExists + ", grantAmountExists=" + grantAmountExists + ", includeInLine2="
				+ includeInLine2 + ", includeInLine2c=" + includeInLine2c + ", includeInLine2d=" + includeInLine2d
				+ ", includeInLine3=" + includeInLine3 + ", includedInLine2=" + includedInLine2 + ", includedInLine2a="
				+ includedInLine2a + ", includedInLine2b=" + includedInLine2b + ", includedInLine2c=" + includedInLine2c
				+ ", includedInLine2d=" + includedInLine2d + ", includedInLine2e=" + includedInLine2e
				+ ", includedInLine2h=" + includedInLine2h + ", includedInLine2i=" + includedInLine2i + ", chSupArrs="
				+ chSupArrs + ", medSupArrs=" + medSupArrs + ", startDate=" + startDate + ", endDate=" + endDate
				+ ", grantStart=" + grantStart + ", monthsActive=" + monthsActive + ", calcStart=" + calcStart
				+ ", calcStartYyyy=" + calcStartYyyy + ", calcStartYyyyn=" + calcStartYyyyn + ", csYm=" + csYm
				+ ", calcStartMm=" + calcStartMm + ", calcStartMmn=" + calcStartMmn + ", csMn=" + csMn
				+ ", calcStartDd=" + calcStartDd + ", calcEnd=" + calcEnd + ", calcEndYyyy=" + calcEndYyyy
				+ ", calcEndYyyyn=" + calcEndYyyyn + ", ceYm=" + ceYm + ", calcEndMm=" + calcEndMm + ", calcEndMmn="
				+ calcEndMmn + ", ceMn=" + ceMn + ", calcEndDd=" + calcEndDd + ", sept=" + sept + ", septYyyy="
				+ septYyyy + ", sYm=" + sYm + ", septMm=" + septMm + ", sMn=" + sMn + ", septDd=" + septDd
				+ ", obligationExists=" + obligationExists + ", notOnly=" + notOnly + ", moved=" + moved + ", exists="
				+ exists + ", status=" + status + ", totAArrsDue=" + totAArrsDue + ", totAArrsRcvd=" + totAArrsRcvd
				+ ", totNArrsDue=" + totNArrsDue + ", totNArrsRcvd=" + totNArrsRcvd + ", afdcChSupDelq=" + afdcChSupDelq
				+ ", afdcChSupInGrace=" + afdcChSupInGrace + ", afdcMedDue=" + afdcMedDue + ", afdcMedRcvd="
				+ afdcMedRcvd + ", afdcMdSupDelq=" + afdcMdSupDelq + ", afdcMdSupInGrace=" + afdcMdSupInGrace
				+ ", nafdcChSupDelq=" + nafdcChSupDelq + ", nafdcChSupInGrace=" + nafdcChSupInGrace + ", nafdcMedDue="
				+ nafdcMedDue + ", nafdcMedRcvd=" + nafdcMedRcvd + ", nafdcMdSupDelq=" + nafdcMdSupDelq
				+ ", nafdcMdSupInGrace=" + nafdcMdSupInGrace + ", totACsDelqRcvd=" + totACsDelqRcvd
				+ ", totNCsDelqRcvd=" + totNCsDelqRcvd + ", totAMsDelqRcvd=" + totAMsDelqRcvd + ", totNMsDelqRcvd="
				+ totNMsDelqRcvd + ", aCsInGraceRcvd=" + aCsInGraceRcvd + ", nCsInGraceRcvd=" + nCsInGraceRcvd
				+ ", aMsInGraceRcvd=" + aMsInGraceRcvd + ", nMsInGraceRcvd=" + nMsInGraceRcvd + ", totNArrsCint="
				+ totNArrsCint + ", totNArrsSint=" + totNArrsSint + ", mthNArrsCint=" + mthNArrsCint + ", totNMedCint="
				+ totNMedCint + ", totNMedSint=" + totNMedSint + ", mthNMedCint=" + mthNMedCint + ", tcArsDue="
				+ tcArsDue + ", tcArsRcv=" + tcArsRcv + ", tcChSupDel=" + tcChSupDel + ", tcCsDelRcv=" + tcCsDelRcv
				+ ", uArsDue=" + uArsDue + ", uArsRcv=" + uArsRcv + ", uChSupDel=" + uChSupDel + ", uCsDelRcv="
				+ uCsDelRcv + ", nArsCintRcv=" + nArsCintRcv + ", nArsSintRcv=" + nArsSintRcv + ", mthNArsIntRcv="
				+ mthNArsIntRcv + ", tcArsCint=" + tcArsCint + ", tcArsCintRcv=" + tcArsCintRcv + ", tcArsSint="
				+ tcArsSint + ", tcArsSintRcv=" + tcArsSintRcv + ", mthTcArsInt=" + mthTcArsInt + ", mthTcArsIntRcv="
				+ mthTcArsIntRcv + ", uArsCint=" + uArsCint + ", uArsCintRcv=" + uArsCintRcv + ", uArsSint=" + uArsSint
				+ ", uArsSintRcv=" + uArsSintRcv + ", mthUArsInt=" + mthUArsInt + ", mthUArsIntRcv=" + mthUArsIntRcv
				+ ", tcChSupInGrace=" + tcChSupInGrace + ", tcCsInGraceRcv=" + tcCsInGraceRcv + ", uChSupInGrace="
				+ uChSupInGrace + ", uCsInGraceRcv=" + uCsInGraceRcv + ", nMedCintRcv=" + nMedCintRcv + ", nMedSintRcv="
				+ nMedSintRcv + ", mthNMedIntRcv=" + mthNMedIntRcv + ", fyStart=" + fyStart + ", fysYyyy=" + fysYyyy
				+ ", fysYm=" + fysYm + ", fysMm=" + fysMm + ", fysMd=" + fysMd + ", fysDd=" + fysDd + ", fyEnd=" + fyEnd
				+ ", fyeYyyy=" + fyeYyyy + ", fyeYm=" + fyeYm + ", fyeMm=" + fyeMm + ", fyeMd=" + fyeMd + ", fyeDd="
				+ fyeDd + ", fyQtr=" + fyQtr + ", work=" + work + ", caseIda=" + caseIda + ", caseId=" + caseId
				+ ", cdn=" + cdn + ", cdn9=" + cdn9 + ", cdn2=" + cdn2 + ", cnt=" + cnt + ", oblgCnt=" + oblgCnt
				+ ", oblgType=" + oblgType + ", oldValue=" + oldValue + ", oldCaseType=" + oldCaseType + ", oldRes2="
				+ oldRes2 + ", newValue=" + newValue + ", newCaseType=" + newCaseType + ", newTypeDate=" + newTypeDate
				+ ", newRest2=" + newRest2 + ", amount=" + amount + ", obligationType=" + obligationType
				+ ", orderType=" + orderType + ", csExtend18=" + csExtend18 + ", serviceType=" + serviceType
				+ ", apCountry=" + apCountry + ", ctCountry=" + ctCountry + ", dateVar=" + dateVar + ", dateVar2="
				+ dateVar2 + ", pagenumber=" + pagenumber + ", changedTime=" + changedTime + ", timeOfEvent="
				+ timeOfEvent + ", commitData=" + commitData + ", nbrOfTables=" + nbrOfTables + ", viewArray="
				+ viewArray + ", respFips=" + respFips + ", initFips=" + initFips + ", mthOrQtr=" + mthOrQtr
				+ ", fiscalYear=" + fiscalYear + ", weo2p57aCnt=" + weo2p57aCnt + ", gApPin=" + gApPin + ", gCtPin="
				+ gCtPin + ", weo2p57aCaseId=" + weo2p57aCaseId + ", weo2p57aCaseType=" + weo2p57aCaseType
				+ ", weo2p57aStatus=" + weo2p57aStatus + ", weo2p57aCdn=" + weo2p57aCdn + ", weo2p57aApStatusCd="
				+ weo2p57aApStatusCd + ", weo2p57aOosCaseType=" + weo2p57aOosCaseType + ", weo2p57aAfdcCaseNbr="
				+ weo2p57aAfdcCaseNbr + ", weo2p57aCaseStartDate=" + weo2p57aCaseStartDate + ", weo2p57aAssistType="
				+ weo2p57aAssistType + ", weo2p57aStatusChgDate=" + weo2p57aStatusChgDate + ", weo2p57aServiceType="
				+ weo2p57aServiceType + ", weo2p57aGApPin=" + weo2p57aGApPin + ", weo2p57aGCtPin=" + weo2p57aGCtPin
				+ ", weo2p57aApCountry=" + weo2p57aApCountry + ", weo2p57aCtCountry=" + weo2p57aCtCountry
				+ ", weo2p57aAmount=" + weo2p57aAmount + ", weo2p57aStartDate=" + weo2p57aStartDate
				+ ", weo2p57aEndDate=" + weo2p57aEndDate + ", weo2p57aObligationType=" + weo2p57aObligationType
				+ ", weo2p57aOrderType=" + weo2p57aOrderType + ", weo2p57aCsExtend18=" + weo2p57aCsExtend18
				+ ", weo2p57aRespFips=" + weo2p57aRespFips + ", weo2p57aInitFips=" + weo2p57aInitFips
				+ ", weo2p57aAfdcChSupDelq=" + weo2p57aAfdcChSupDelq + ", weo2p57aAfdcChSupInGrace="
				+ weo2p57aAfdcChSupInGrace + ", weo2p57aAfdcMedDue=" + weo2p57aAfdcMedDue + ", weo2p57aAfdcMedRcvd="
				+ weo2p57aAfdcMedRcvd + ", weo2p57aAfdcMdSupDelq=" + weo2p57aAfdcMdSupDelq
				+ ", weo2p57aAfdcMdSupInGrace=" + weo2p57aAfdcMdSupInGrace + ", weo2p57aNafdcChSupDelq="
				+ weo2p57aNafdcChSupDelq + ", weo2p57aNafdcChSupInGrace=" + weo2p57aNafdcChSupInGrace
				+ ", weo2p57aNafdcMedDue=" + weo2p57aNafdcMedDue + ", weo2p57aNafdcMedRcvd=" + weo2p57aNafdcMedRcvd
				+ ", weo2p57aNafdcMdSupDelq=" + weo2p57aNafdcMdSupDelq + ", weo2p57aNafdcMdSupInGrace="
				+ weo2p57aNafdcMdSupInGrace + ", weo2p57aTotACsDelqRcvd=" + weo2p57aTotACsDelqRcvd
				+ ", weo2p57aTotAMsDelqRcvd=" + weo2p57aTotAMsDelqRcvd + ", weo2p57aACsInGraceRcvd="
				+ weo2p57aACsInGraceRcvd + ", weo2p57aAMsInGraceRcvd=" + weo2p57aAMsInGraceRcvd
				+ ", weo2p57aTotNCsDelqRcvd=" + weo2p57aTotNCsDelqRcvd + ", weo2p57aTotNMsDelqRcvd="
				+ weo2p57aTotNMsDelqRcvd + ", weo2p57aNCsInGraceRcvd=" + weo2p57aNCsInGraceRcvd
				+ ", weo2p57aNMsInGraceRcvd=" + weo2p57aNMsInGraceRcvd + ", weo2p57aTotNArrsCint="
				+ weo2p57aTotNArrsCint + ", weo2p57aTotNArrsSint=" + weo2p57aTotNArrsSint + ", weo2p57aMthNArrsCint="
				+ weo2p57aMthNArrsCint + ", weo2p57aTotNMedCint=" + weo2p57aTotNMedCint + ", weo2p57aTotNMedSint="
				+ weo2p57aTotNMedSint + ", weo2p57aMthNMedCint=" + weo2p57aMthNMedCint + ", weo2p57aTotAArrsDue="
				+ weo2p57aTotAArrsDue + ", weo2p57aTotAArrsRcvd=" + weo2p57aTotAArrsRcvd + ", weo2p57aTotNArrsDue="
				+ weo2p57aTotNArrsDue + ", weo2p57aTotNArrsRcvd=" + weo2p57aTotNArrsRcvd + ", weo2p57aTcArsDue="
				+ weo2p57aTcArsDue + ", weo2p57aTcArsRcv=" + weo2p57aTcArsRcv + ", weo2p57aTcChSupDel="
				+ weo2p57aTcChSupDel + ", weo2p57aTcCsDelRcv=" + weo2p57aTcCsDelRcv + ", weo2p57aUArsDue="
				+ weo2p57aUArsDue + ", weo2p57aUArsRcv=" + weo2p57aUArsRcv + ", weo2p57aUChSupDel=" + weo2p57aUChSupDel
				+ ", weo2p57aUCsDelRcv=" + weo2p57aUCsDelRcv + ", weo2p57aNArsCintRcv=" + weo2p57aNArsCintRcv
				+ ", weo2p57aNArsSintRcv=" + weo2p57aNArsSintRcv + ", weo2p57aMthNArsIntRcv=" + weo2p57aMthNArsIntRcv
				+ ", weo2p57aTcArsCint=" + weo2p57aTcArsCint + ", weo2p57aTcArsCintRcv=" + weo2p57aTcArsCintRcv
				+ ", weo2p57aTcArsSint=" + weo2p57aTcArsSint + ", weo2p57aTcArsSintRcv=" + weo2p57aTcArsSintRcv
				+ ", weo2p57aMthTcArsInt=" + weo2p57aMthTcArsInt + ", weo2p57aMthTcArsIntRcv=" + weo2p57aMthTcArsIntRcv
				+ ", weo2p57aUArsCint=" + weo2p57aUArsCint + ", weo2p57aUArsCintRcv=" + weo2p57aUArsCintRcv
				+ ", weo2p57aUArsSint=" + weo2p57aUArsSint + ", weo2p57aUArsSintRcv=" + weo2p57aUArsSintRcv
				+ ", weo2p57aMthUArsInt=" + weo2p57aMthUArsInt + ", weo2p57aMthUArsIntRcv=" + weo2p57aMthUArsIntRcv
				+ ", weo2p57aTcChSupInGrace=" + weo2p57aTcChSupInGrace + ", weo2p57aTcCsInGraceRcv="
				+ weo2p57aTcCsInGraceRcv + ", weo2p57aUChSupInGrace=" + weo2p57aUChSupInGrace
				+ ", weo2p57aUCsInGraceRcv=" + weo2p57aUCsInGraceRcv + ", weo2p57aNMedCintRcv=" + weo2p57aNMedCintRcv
				+ ", weo2p57aNMedSintRcv=" + weo2p57aNMedSintRcv + ", weo2p57aMthNMedIntRcv=" + weo2p57aMthNMedIntRcv
				+ ", weo2p57aExists=" + weo2p57aExists + ", weo2p57aOldValueCs=" + weo2p57aOldValueCs
				+ ", weo2p57aTimeOfEvent=" + weo2p57aTimeOfEvent + ", weo2p57aOldValue=" + weo2p57aOldValue
				+ ", weo2p57aNewValue=" + weo2p57aNewValue + ", weo2p57aOldValueOos=" + weo2p57aOldValueOos
				+ ", weo2p57aChildDob=" + weo2p57aChildDob + ", weo2p57aInsuOrderedCount=" + weo2p57aInsuOrderedCount
				+ ", weo2p57aGrantStart=" + weo2p57aGrantStart + ", weo2p57aOblgCnt=" + weo2p57aOblgCnt
				+ ", weo2p57aOblgType=" + weo2p57aOblgType + "]";
	}
}